local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {
		function getArticle( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "an " : "a ";
		}

		function getArticleCapitalized( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "An " : "A ";
		}

	};
}

if (!("Tactical" in gt.Const.Strings))
{
	gt.Const.Strings.Tactical <- {};
}

if (!("World" in gt.Const.Strings))
{
	gt.Const.Strings.World <- {};
}

gt.Const.Strings.Quantity <- [
	"1st",
	"2nd",
	"3rd",
	"4th",
	"5th",
	"6th",
	"7th",
	"8th",
	"9th",
	"10th",
	"11th",
	"12th",
	"13th",
	"14th",
	"15th",
	"16th",
	"17th",
	"18th",
	"19th",
	"20th"
];
gt.Const.Strings.Amount <- [
	"no",
	"one",
	"two",
	"three",
	"four",
	"five",
	"six",
	"seven",
	"eight",
	"nine",
	"ten",
	"eleven",
	"twelve",
	"thirteen",
	"fourteen",
	"fifteen",
	"sixteen",
	"seventeen",
	"eighteen",
	"nineteen",
	"twenty",
	"twenty-one",
	"twenty-two",
	"twenty-three",
	"twenty-four",
	"twenty-five",
	"twenty-six",
	"twenty-seven",
	"twenty-eight",
	"twenty-nine",
	"thirty"
];
gt.Const.Strings.AmountC <- [
	"No",
	"One",
	"Two",
	"Three",
	"Four",
	"Five",
	"Six",
	"Seven",
	"Eight",
	"Nine",
	"Ten",
	"Eleven",
	"Twelve",
	"Thirteen",
	"Fourteen",
	"Fifteen",
	"Sixteen",
	"Seventeen",
	"Eighteen",
	"Nineteen",
	"Twenty",
	"Twenty-one",
	"Twenty-two",
	"Twenty-three",
	"Twenty-four",
	"Twenty-five",
	"Twenty-six",
	"Twenty-seven",
	"Twenty-eight",
	"Twenty-nine",
	"Thirty"
];
gt.Const.Strings.Difficulty <- [
	"Beginner",
	"Veteran",
	"Expert"
];
gt.Const.Strings.EntityName <- [
	"Necromancer",
	"Wiederganger",
	"Armored Wiederganger",
	"Fallen Hero",
	"Rachegeist",
	"Ancient Auxiliary",
	"Ancient Legionary",
	"Ancient Honor Guard",
	"Ancient Priest",
	"The Conqueror",
	"Necrosavant",
	"Geist",
	"Nachzehrer",
	"Orc Young",
	"Orc Berserker",
	"Orc Warrior",
	"Orc Warlord",
	"Militia",
	"Militia Marksman",
	"Militia Veteran",
	"Militia Captain",
	"Bounty Hunter",
	"Peasant",
	"Caravan Hand",
	"Caravan Guard",
	"Caravan Cart",
	"Footman",
	"Zweihander",
	"Billman",
	"Arbalester",
	"Standard Bearer",
	"Sergeant",
	"Knight",
	"Donkey",
	"Brigand Thug",
	"Brigand Poacher",
	"Brigand Marksman",
	"Brigand Raider",
	"Brigand Leader",
	"Goblin Ambusher",
	"Goblin Skirmisher",
	"Goblin Overseer",
	"Goblin Shaman",
	"Goblin Wolfrider",
	"Wolf",
	"Wardog",
	"Armored Wardog",
	"Mercenary",
	"Mercenary",
	"Swordmaster",
	"Hedge Knight",
	"Master Archer",
	"Greenskin Catapult",
	"Cultist",
	"Direwolf",
	"Lindwurm",
	"Unhold",
	"Unhold",
	"Unhold",
	"Webknecht",
	"Webknecht Eggs",
	"Alp",
	"Hexe",
	"Schrat",
	"Sapling",
	"Wildman",
	"Kraken",
	"Irrlicht",
	"Fallen Betrayer",
	"Nightmare",
	"Barbarian Thrall",
	"Barbarian Reaver",
	"Barbarian Chosen",
	"Barbarian Drummer",
	"Barbarian Beastmaster",
	"Armored Unhold",
	"Armored Unhold",
	"Barbarian King",
	"Warhound",
	"The Ijirok",
	"Barbarian Madman",
	"Serpent",
	"Ifrit",
	"Hyena",
	"Conscript",
	"Gunner",
	"Officer",
	"Engineer",
	"Assassin",
	"Indebted",
	"Gladiator",
	"Mortar",
	"Nomad Cutthroat",
	"Nomad Outlaw",
	"Nomad Slinger",
	"Nomad Archer",
	"Nomad Leader",
	"Desert Stalker",
	"Nomad Executioner",
	"Blade Dancer",
	"Citizen",
	"The Lorekeeper",
	"Lorekeeper\'s Apparition",
	"Phylactery",
	"Lost Treasure Hunter",
	"Screaming Skull"
];
gt.Const.Strings.EntityNamePlural <- [
	"Necromancers",
	"Wiedergangers",
	"Armored Wiedergangers",
	"Fallen Heroes",
	"Rachegeists",
	"Ancient Auxiliaries",
	"Ancient Legionaries",
	"Ancient Honor Guards",
	"Ancient Priests",
	"The Conqueror",
	"Necrosavants",
	"Geists",
	"Nachzehrers",
	"Orc Young",
	"Orc Berserkers",
	"Orc Warriors",
	"Orc Warlords",
	"Militia",
	"Militia Marksmen",
	"Militia Veterans",
	"Militia Captains",
	"Bounty Hunters",
	"Peasants",
	"Caravan Hands",
	"Caravan Guards",
	"Caravan Carts",
	"Footmen",
	"Zweihanders",
	"Billmen",
	"Arbalesters",
	"Standard Bearers",
	"Sergeants",
	"Knights",
	"Donkeys",
	"Brigand Thugs",
	"Brigand Poachers",
	"Brigand Marksmen",
	"Brigand Raiders",
	"Brigand Leaders",
	"Goblin Ambushers",
	"Goblin Skirmishers",
	"Goblin Overseers",
	"Goblin Shamans",
	"Goblin Wolfriders",
	"Wolves",
	"Wardogs",
	"Armored Wardogs",
	"Mercenaries",
	"Mercenaries",
	"Swordmasters",
	"Hedge Knights",
	"Master Archers",
	"Greenskin Catapults",
	"Cultists",
	"Direwolves",
	"Lindwurms",
	"Unholds",
	"Unholds",
	"Unholds",
	"Webknechts",
	"Webknecht Eggs",
	"Alps",
	"Hexen",
	"Schrats",
	"Saplings",
	"Wildmen",
	"Kraken",
	"Irrlicht",
	"Fallen Betrayers",
	"Nightmares",
	"Barbarian Thralls",
	"Barbarian Reavers",
	"Barbarian Chosen",
	"Barbarian Drummers",
	"Barbarian Beastmasters",
	"Armored Unholds",
	"Armored Unholds",
	"Barbarian Kings",
	"Warhounds",
	"Beasts of Winter",
	"Barbarian Madmen",
	"Serpents",
	"Ifrits",
	"Hyenas",
	"Conscripts",
	"Gunners",
	"Officers",
	"Engineers",
	"Assassins",
	"Indebted",
	"Gladiators",
	"Mortars",
	"Nomad Cutthroats",
	"Nomad Outlaws",
	"Nomad Slingers",
	"Nomad Archers",
	"Nomad Leaders",
	"Desert Stalkers",
	"Nomad Executioners",
	"Blade Dancers",
	"Citizens",
	"The Lorekeeper",
	"Lorekeeper\'s Apparition",
	"Phylacteries",
	"Lost Treasure Hunters",
	"Screaming Skulls"
];
gt.Const.Strings.Tactical.EntityName <- {
	Boulder = "Boulder",
	Ruin = "Ruin",
	Shrubbery = "Shrubbery",
	Tree = "Tree",
	Brush = "Brush",
	Cartwheel = "Old Cartwheel",
	RuinedPillar = "Ruined Pillar",
	Cart = "Caravan Cart",
	Donkey = "Donkey",
	Plant = "Plant"
};
gt.Const.Strings.Tactical.EntityDescription <- {
	Boulder = "A large stone boulder. Blocks movement and line of sight.",
	Ruin = "Ruins from an age long past.",
	Shrubbery = "Very dense shrubbery that blocks movement and line of sight.",
	Tree = "A large tree with a massive trunk.",
	TreeSwamp = "This tree is rotten and long dead.",
	TreeTrunk = "A treetrunk half covered in foul water.",
	Brush = "Very dense shrubbery that blocks movement and line of sight.",
	Cartwheel = "The old and broken wheel of an oxcart.",
	RuinedPillar = "TODO",
	Cart = "A cart full of trading goods.",
	Donkey = "A donkey used for pulling heavy carts.",
	Plant = "An exotic plant that blocks movement and line of sight."
};
gt.Const.Strings.FootprintsType <- [
	"",
	"Northern soldiers",
	"Gilded soldiers",
	"A caravan",
	"Peasants",
	"Militia",
	"Refugees",
	"Brigands",
	"Undead",
	"Orcs",
	"Goblins",
	"Barbarians",
	"Nomads",
	"Direwolves",
	"Nachzehrers",
	"Hyenas",
	"Serpents",
	"Webknechts",
	"Unholds",
	"Alps",
	"Hexen",
	"Schrats",
	"A Kraken",
	"Ifrits",
	"Lindwurms",
	"Mercenaries"
];
gt.Const.Strings.ShipNames <- [
	"Summer Daze",
	"Merry Mist",
	"Howl of the Sea",
	"Coral Secret",
	"Sandy Bay",
	"Lady of the Sea",
	"Solitaire",
	"Brunhild",
	"Mathilda",
	"Comet",
	"Tetrarch",
	"Lofjord",
	"Autumn Wind",
	"Poundmaker",
	"Brakel",
	"Seven Stars",
	"Dark Omen",
	"Concord",
	"Albatros",
	"Golden Horse",
	"Sea Nymph",
	"Twisted Fate",
	"King\'s Bounty",
	"Bald Monk",
	"Golden Sun",
	"Vanity",
	"Brazen",
	"Tiger\'s Claw",
	"Sycamore",
	"Noble Runner",
	"Bleak Moon",
	"Clansman",
	"Whale\'s Voyage",
	"Quickmatch",
	"Blackfly",
	"Ejnar Erikson",
	"Lindwurm",
	"Supreme",
	"Griffon",
	"Axford",
	"Bertha",
	"Seagull",
	"Belzebub"
];
gt.Const.Strings.MercenaryCompanyNames <- [
	"Iron Ravens",
	"Golden Order",
	"Swords of the South",
	"Wolves of Bleak Forest",
	"Black Shields",
	"Iron Crown Company",
	"Radobrecht\'s Swords",
	"Whistling Arrows",
	"Azure Boars",
	"Fang and Coin",
	"Red Legion",
	"Hungry Hounds",
	"Crimson Daggers",
	"King\'s End Company",
	"Black Company",
	"Second Sons",
	"Walther\'s Fellowship",
	"Grudgebringers",
	"Bernhard\'s Bears",
	"Silver Claw",
	"Iron Brotherhood",
	"Orcbane Company",
	"Iron Covenant",
	"Unbroken Third",
	"Dogs of War",
	"Falkenberg\'s Legion",
	"Free Men",
	"Lords of War",
	"Northern Company",
	"Forsaken Returned",
	"White Company",
	"Widowmakers",
	"Cold Hearts Company",
	"Burning Sun Company",
	"Chosen Few",
	"Dead Men",
	"Bronzeheads",
	"Markland Pikes",
	"Hammerguard",
	"Crowntakers",
	"Silverreach Spears",
	"Iron Pact",
	"Blood Bound",
	"Bulwark",
	"Dawn\'s March",
	"Sons of Winter",
	"Company of the River House",
	"Flaming Comet Company",
	"Grand Company",
	"Rightful Ravagers",
	"Forsaken Brigade",
	"Battle\'s Chosen",
	"Bringers of Peace",
	"Shields of the Night",
	"Mongrels",
	"Bone Wardens",
	"Lost Legion"
];
gt.Const.Strings.NobleHouseNames <- [
	"Grimmund",
	"Weilburg",
	"Armsberg",
	"Gota",
	"Eisenstein",
	"Grauwall",
	"Rabenholt",
	"Sommerwein",
	"Winterhall",
	"Ruhmolt",
	"Adelreich",
	"Perowinger",
	"Eiglof",
	"Berengar",
	"Gunbald",
	"Goswin",
	"Adelheim",
	"Ammondt",
	"Bartholin",
	"Eberlin",
	"Folsach",
	"Hedin",
	"Horn",
	"Niedergard",
	"Rosenving",
	"Thurah",
	"Kaltenborn",
	"Krieger",
	"Steinwall",
	"Harkon",
	"Osten"
];
gt.Const.Strings.CityStateNames <- [
	"Dahab",
	"Kabira",
	"Ras Sanan",
	"Tanwir",
	"Azim Shab",
	"Tarwa",
	"Hakim Al Ramal",
	"Karrakan",
	"Al-Hazred",
	"Al-Hazif",
	"Quadim",
	"Hikma",
	"El-Hadet",
	"Al-Anwar"
];
gt.Const.Strings.CityStateTitles <- [
	"City State of",
	"City of",
	"Protectorate of",
	"Realm of",
	"Grand City of",
	"Free City of",
	"Holy City of"
];
gt.Const.Strings.BusinessReputation <- [
	"Treacherous",
	"Incompetent",
	"Unreliable",
	"Unknown",
	"Recognized",
	"Reliable",
	"Competent",
	"Professional",
	"Reputable",
	"Famed",
	"Great",
	"Glorious",
	"Fabled",
	"Legendary",
	"Invincible",
	"Immortal"
];
gt.Const.Strings.MoralReputation <- [
	"Dreaded",
	"Cruel",
	"Merciless",
	"Notorious",
	"Neutral",
	"Neutral",
	"Kind",
	"Good",
	"Chivalrous",
	"Saintly"
];
gt.Const.Strings.Relations <- [
	"Hostile",
	"Threatening",
	"Unfriendly",
	"Cold",
	"Neutral",
	"Neutral",
	"Open",
	"Friendly",
	"Very Friendly",
	"Allied"
];
gt.Const.Strings.Tactical.TerrainName <- [
	"None",
	"Dirt Road",
	"Clay Road",
	"Cobblestone Road",
	"Grassland",
	"Dirt",
	"Forest",
	"Muddy Earth",
	"Plashy Grass",
	"Murky Water",
	"Steppe",
	"Dry Steppe",
	"Tundra",
	"Snow",
	"Light Snow",
	"Stone",
	"Stone",
	"Sand",
	"Shallow Water"
];
gt.Const.Strings.Tactical.TerrainDescription <- [
	"None",
	"A dirt road originating from constant use by humans and animals.",
	"A primitve road consisting of tamped clay.",
	"A cobblestone road used for carriages and larger vehicles.",
	"Short grass on flat and solid ground.",
	"Bare and flat earth with barely any vegetation.",
	"Forest ground covered in a thick and soft mossy layer.",
	"Dark and muddy earth.",
	"Mostly firm ground covered in tall and soft grass.",
	"Shallow, murky water covering a soft and muddy ground.",
	"Flat and firm ground covered with dry and shriveled grass.",
	"Hard patches of earth completely dried out by sun and heat.",
	"Flat and arid ground covered in rough grasses and weeds.",
	"Frozen ground covered in a thick layer of snow.",
	"Frozen ground covered in a light layer of snow.",
	"Smooth stone ground granting a good footing.",
	"Rough stone ground.",
	"Burning hot desert sand.",
	"Clear and shallow water."
];
gt.Const.Strings.UI <- {
	Introduction = "You soak in the cool morning air. As the sun slowly rises, so does a new chapter in your life begin. After years of bloodying your sword for meager pay you\'ve saved up enough crowns to start your very own mercenary company. With you are %allbrothers% with whom you\'ve fought before side by side in the shieldwall. You are their commander now, the leader of the %companyname%.\n\nAs you travel the lands you should hire new men in the villages and cities to fill your ranks. Many who offer their services will have never picked up a real weapon before. Maybe they are desperate, maybe they are greedy for quick spoils of war. Most of them will die on the battlefield. But do not be discouraged. Such is the mercenary life, and the next village will always have new men eagerly looking for a new start in life.\n\nThe lands are dangerous these times. Robbers and pillagers lay in ambush by the roads, wild beasts roam the dark forests and orc tribes are restless in the swamps to the east. There are rumors even of dark magic being at work, the dead rising from their graves and walking again. There is plenty of opportunity to earn good money, whether by taking on contracts you can find in the villages, cities and strongholds all over the land, or by venturing out on your own to explore and raid.\n\nYour men look to you to give a command. They live and die for the %companyname% now.\n\n[color=#bd9d71]EARLY ACCESS DISCLAIMER: This version is still heavily work in progress and does not represent the final quality of the product. Features may be incomplete or missing, the UI is unskinned as of yet, there will be bugs, and the balancing and progression of the economy, resources and enemies may need tweaking and can be too challenging or easy occasionally. A lot of additional content will be added over the course of the Early Access, including more enemies, items, contracts, terrain types, unique locations, story events and other features.[/color]",
	FleeDialogueConsequences = "Sometimes it\'s better to do a tactical retreat in order to live and fight another day. The men will attempt to reach the edges of the map by themselves and then safely retreat. However, the enemy may catch up, and anyone currently engaged may not be able to get away unscathed or even alive.",
	RetreatDialogueConsequences = "The enemy is battered and beaten. Those few still alive scatter away in all directions. Will you hunt them down to claim their heads and possessions, or declare the battle won?"
};
gt.Const.Strings.AlpStateName <- [
	"",
	"Existing partly in dreams",
	"Existing partly in dreams",
	"Existing mostly in dreams",
	"Existing mostly in dreams"
];
gt.Const.Strings.BodyPartName <- [
	"corps",
	"tête"
];
gt.Const.Strings.ItemSlotName <- [
	"Corps",
	"Tête",
	"Main Dominante",
	"Main Non-Dominante",
	"Accessoire",
	"Sac"
];
gt.Const.Strings.World.TimeOfDay <- [
	"Aube",
	"Matin",
	"Midi",
	"Après-Midi",
	"Soir",
	"Crépuscule",
	"Nuit",
	"Aube"
];
gt.Const.Strings.Direction <- [
	"north",
	"north-east",
	"south-east",
	"south",
	"south-west",
	"north-west",
	"<undefined>"
];
gt.Const.Strings.Direction8 <- [
	"au nord",
	"au nord-est",
	"à l\'est",
	"au sud-est",
	"au sud",
	"au sud-ouest",
	"à l\'ouest",
	"au nord-west"
];
gt.Const.Strings.Terrain <- [
	"",
	"in the ocean",
	"on the plains",
	"in the swamps",
	"on the hills",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the mountains",
	"",
	"",
	"in the snow",
	"in the wastelands",
	"in the tundra",
	"in the steppe",
	"on the shore",
	"in the desert",
	"in the wetlands"
];
gt.Const.Strings.TerrainAlternative <- [
	"",
	"",
	"on plains",
	"in the swamp",
	"on a hill",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the forest",
	"on a mountain",
	"on plains",
	"on plains",
	"in the snow",
	"",
	"in the tundra",
	"on steppe",
	"",
	"in the desert",
	"in wetlands"
];
gt.Const.Strings.TerrainShort <- [
	"",
	"bay",
	"plains",
	"swamp",
	"hills",
	"forest",
	"forest",
	"forest",
	"forest",
	"mountain",
	"",
	"",
	"snow",
	"wastelands",
	"tundra",
	"steppe",
	"shore",
	"",
	"desert",
	"hills",
	"wetlands"
];
gt.Const.Strings.TerrainRegionNames <- [
	[],
	[
		"Stormy Sea",
		"Kraken\'s Refuge",
		"White Horses Sea",
		"Thousand Gulls Sea",
		"Deep Depths",
		"Rainy Ocean",
		"Unbound Ocean",
		"Tempest Ocean",
		"Thunder Sea",
		"Great Sea",
		"Surging Sea",
		"Pearl Sea",
		"Howling Sea",
		"Cruel Sea",
		"Arching Tides Ocean",
		"Whispering Waves Sea",
		"Soft Ripple Sea",
		"Green Sea",
		"Sea of Turning Tides",
		"Wailing Ocean",
		"Foamy Shallows",
		"Murky Tide Ocean",
		"Shimmering Expanse",
		"Azure Expanse",
		"The Raging Gulf",
		"The Shimmering Depths"
	],
	[
		"Vendland",
		"Speedwell Fields",
		"Plainshire",
		"Vinland",
		"Lowlands",
		"Windlands",
		"Wide Watch",
		"Glaucious Domain",
		"Rich Meadows",
		"Markland",
		"Fast Clouds County",
		"Fairdale",
		"Fleetfeet\'s Range",
		"Wanderer\'s Boon",
		"Valeshire",
		"Ridland",
		"Greenfold",
		"Hogfolk",
		"Durum",
		"Shallowford",
		"Two Fields",
		"Kingmill",
		"Minceacre",
		"Glendale",
		"Brillfold",
		"Kindon",
		"Greenmere",
		"Mooseridge",
		"Altmark",
		"Neumark",
		"Fair Range",
		"Middlemark",
		"Grasslands",
		"Moss Valley",
		"Wideacre",
		"Southbloom",
		"Dawnland",
		"Oak Wood Meadows",
		"Southwind Acres",
		"Meadowcove",
		"Willow\'s Fields",
		"Grand View Pastures",
		"Nightingale Valley",
		"Silversage Fields",
		"Heartsong\'s Range"
	],
	[
		"Black Marshes",
		"Dead Ponds",
		"Tar Fields",
		"Peatfold",
		"Suffocating Bog",
		"Eerie Marshes",
		"Black Morass",
		"Sticky Wallow",
		"Dreaded Mire",
		"Murky Swamplands",
		"Mortun",
		"Blackfan",
		"Gallowsbog",
		"Dungslump",
		"Houndsmarsh",
		"Shipreath Marsh",
		"Cursed Lands",
		"Grimdowns",
		"The Reeds",
		"Froghold",
		"Spidergrove",
		"Duke\'s Demise",
		"Bottomless Pits",
		"Poisonbreath Marshes",
		"Froglickers Grove",
		"Deadbottom",
		"The Wetlands",
		"The Marshlands",
		"Black Mud",
		"Desolate Moor",
		"Black Fumes Polder",
		"Endless Polder",
		"Peat Basin",
		"Riverland Glades",
		"Southland Bowels",
		"Azure Marsh",
		"Thousand Mirrors Bog",
		"The Narrow Quag",
		"Glades of Decay",
		"Ashen Wetlands",
		"Savage Bog",
		"Mire of the Whisp",
		"Forbidden Waters",
		"Dreadmoor"
	],
	[
		"Bonefold Barrow",
		"Knight\'s Axe Hills",
		"Skullsbreath Mound",
		"Ancient Knolls",
		"Oldlock Hills",
		"The Hummocks",
		"Knowesfold",
		"Ancient Cairns",
		"Humming Hills",
		"Sharp Rocks",
		"Misty Barrows",
		"Boulderhills",
		"Scree Barrows",
		"Bed Load Knolls",
		"Ghost Hills",
		"Banshee Mounds",
		"Shinglehumps",
		"Earthwatch Hills",
		"Giant\'s Pebbles",
		"Buried Snake Hills",
		"Skullslide Hills",
		"Rustcave Hills",
		"Witchmount Hills",
		"Juniper Hills",
		"White Goat Mounds",
		"Barum",
		"The Reach",
		"Whispering Hills",
		"The Bronze Hills",
		"Willowshire Hillside",
		"The Scarlet Hills",
		"Giant\'s Slopes",
		"The Gloomy Hills",
		"The Collapsing Hills"
	],
	[
		"Bleak Forest",
		"Dire Woods",
		"Dismal Woods",
		"Dusky Forest",
		"Scoundrels\' Forest",
		"Boar Woods",
		"Bandit\'s Rest",
		"Splinterdale",
		"Spiderwood",
		"Tickbrake",
		"Druid\'s Grove",
		"Brittle Branch Woods",
		"White Wolf\'s Home",
		"Ravenhold",
		"Needlegrove",
		"Rustling Thicket",
		"Mossy Pine Woods",
		"Crows Nest",
		"Black Forest",
		"Prowlers Woods",
		"Gloomy Woods",
		"Wolfwood",
		"Black Woods",
		"Murmuring Woods",
		"Dark Thorn Wilds",
		"Hedgehog Thicket",
		"Misty Covert",
		"Borderdale",
		"Temple Grove",
		"Wretched Woods",
		"Elder Woods",
		"Deep Covert",
		"Macaw Woods",
		"Hexenwald"
	],
	[],
	[
		"Ancient Forest",
		"Ranger\'s Rest",
		"Valley of the Deer",
		"Oldgrowth",
		"Rampants",
		"Ironoak Grove",
		"Hunter\'s Bosk",
		"Royal Grounds",
		"Sylvan Woods",
		"Fox and Hare Woods",
		"Snapping Twig Forest",
		"Antlerfold",
		"Old Forest",
		"Greenwood Forest",
		"Mossy Woods",
		"Misty Woods",
		"The Sea of Trees",
		"Timberland",
		"Whispering Groves",
		"Grand Hare Woods",
		"Chestnut Grove",
		"Snake\'s Covert",
		"Blackwood Forest",
		"Stormy Woods",
		"Rustling Thicket",
		"Wicked Woods",
		"Gray Toad Woodlands",
		"Treewalker Woodlands",
		"Jagged Woods",
		"Stag\'s Grounds",
		"Crowned Oak Forest",
		"Elderberry Woods",
		"Elm Grove",
		"Black Mole Woods",
		"Brookwood",
		"Springwood",
		"Everwoods"
	],
	[
		"Red Worm Woods",
		"Fiery Woods",
		"Smoldering Woods",
		"Ember Forest",
		"Vibrant Grove",
		"Foxfold Forest",
		"Somerhurst",
		"Fireander",
		"Bloodcut Growth",
		"Burnend",
		"Rustdroop",
		"Blood Woods",
		"Blazing Forest",
		"Vermillion Woods",
		"Crimson Forest",
		"Auburn Woods",
		"Redwood",
		"Badger\'s Covert",
		"Birch Timberland",
		"Waterwood Forest",
		"Pyrewood",
		"Beatroot Wilds",
		"Bogwood Grove",
		"Yellowleaf\'s Range",
		"Bloodbloom Woods",
		"Redbark Forest",
		"Firerock Grove"
	],
	[
		"Spine of the World",
		"Sleeping Giants Back",
		"Jagged Spires",
		"Wall of the Gods",
		"Dreaded Rocks",
		"Rocky Ridge",
		"Jagged Summit",
		"Silver Ridge",
		"Misty Summit",
		"Iron Mountains",
		"Goathorns",
		"Dragonteeth",
		"Highrise",
		"Eagleflight",
		"Grimroof",
		"Dunspike",
		"Dreadhorn",
		"Ravensbeak",
		"Mount Bulkhead",
		"Bulwark",
		"Cloddheads",
		"Browslopes",
		"Hero\'s Fall",
		"Yawning Gaps",
		"Mammothshoulders",
		"Swellpike Heights",
		"Bald Crown",
		"Cloudcrest",
		"Evermist Mountains",
		"Slaughtermount",
		"The Rift",
		"The Thundering Peaks",
		"Decayed Heights",
		"The Glistening Heights",
		"Deserted Rise",
		"The Vast Rise",
		"Moonlit Peaks",
		"The Ashen Pinnacle",
		"The Bare Peaks",
		"The Shadow Mountains",
		"Grimestone Peaks",
		"Brimstone Shoulders",
		"Iron Peaks"
	],
	[],
	[],
	[
		"White Waste",
		"Frozen Plains",
		"Sea of Snow",
		"White Wilderness",
		"Silver Plains",
		"Howling Wastes",
		"Silver Flats",
		"Everwinter",
		"Frozen North",
		"World\'s Rim",
		"Coldend",
		"Wintermore",
		"Icemark",
		"Spikewind",
		"Iceblade Dale",
		"Silversand Hold",
		"Frostfold",
		"Icehenge",
		"Frozen Burrows",
		"Aurora Flats",
		"Frostfinger\'s Realm",
		"Nevermelting Hold",
		"The Pale Expanse",
		"Desert of Mirrors",
		"The Ghostly Plains",
		"Chillwind Flatlands",
		"The Glazed Valley",
		"The Howling Desert",
		"The Powder Plains",
		"Snowbank"
	],
	[],
	[
		"Northmark",
		"Tablelands",
		"Scragglands",
		"Norshire",
		"Barescrub",
		"Forefathers\' Highlands",
		"Skyreach",
		"Clan\'s Claim",
		"Rugged Flats",
		"Northern Clanlands",
		"Northern Reaches",
		"Ragwilds",
		"Barrens",
		"Ragnar\'s Range",
		"Pagan Heathland",
		"Ruffmuir",
		"Windlands",
		"Angbride",
		"Baleford",
		"Bleakwolds",
		"Nordlands",
		"Glenmore Barrows",
		"Woldwich",
		"Kinmere",
		"Northurst",
		"Norenford",
		"Holmburn",
		"The Dreary Barrens"
	],
	[
		"Scrublands",
		"Drylands",
		"Torched Plains",
		"Red Lowlands",
		"Scorching Shire",
		"Golden Valley",
		"Southern Steppe",
		"Southmark",
		"The Scald",
		"Bleached Bone Dale",
		"Droughtshire",
		"Sunpan",
		"The Dryweeds",
		"Thornvale",
		"Bronze Flats",
		"Dire Hold",
		"Parcheim",
		"Smallriver Hold",
		"Razorshrub",
		"Gnarlheim",
		"Gritstone",
		"Suderos",
		"Suderland",
		"Solsweald",
		"Rustyblade Mesa",
		"Muskena",
		"Solstein",
		"Southwatch",
		"Sunreach",
		"Sandshear",
		"Skauna",
		"Caskain",
		"Maraman",
		"Jundland",
		"The Borderlands"
	],
	[],
	[
		"Silver Sands",
		"Dead Sands",
		"Golden Flats",
		"Timeless Sands",
		"Glittering Sands",
		"Scorching Desert",
		"The Emptiness",
		"The Burning Barrens",
		"Southern Sands",
		"Dusty Desert",
		"Sea of Sand",
		"Land of the Sun",
		"The Great Desert",
		"Neverending Sands",
		"Southern Reach",
		"Mumbling Sands",
		"Whispering Sands",
		"Shifting Sands",
		"Moaning Sands",
		"Sparkling Sands",
		"Glistening Flats",
		"Dry Wastes"
	],
	[
		"The Lost Oasis",
		"Green Shallows",
		"Emerald Bassin",
		"Pearl of the South",
		"Fruitful Shallows",
		"Springs of Life",
		"Gift of God",
		"Prophet\'s Salvation",
		"The Wetlands"
	]
];
gt.Const.Strings.Distance <- [
	"près",
	"pas loin",
	"pas très loin",
	"une certaine distance",
	"loin",
	"très loin"
];
gt.Const.Strings.PartyStrength <- [
	"Puny",
	"Weak",
	"Average",
	"Strong",
	"Dangerous",
	"Deadly",
	"Invincible"
];
gt.Const.Strings.EngageEnemyNumbers <- [
	"Un peu",
	"Quelques",
	"Un peu Beaucoup",
	"Beaucoup",
	"Énormément"
];
gt.Const.Strings.InventoryHeader <- [
	"Donkey",
	"Cart",
	"Wagon",
	"Big Wagon"
];
gt.Const.Strings.InventoryUpgradeHeader <- [
	"Buy a Cart",
	"Buy a Wagon",
	"Buy a Big Wagon"
];
gt.Const.Strings.InventoryUpgradeText <- [
	"buy a cart",
	"buy a wagon",
	"buy a big wagon"
];
gt.Const.Strings.InventoryUpgradeCosts <- [
	"5,000",
	"10,000",
	"20,000"
];
gt.Const.Strings.PerkName <- {
	Bullseye = "Entre les Deux Yeux",
	Ballistics = "Ballistique",
	Berserk = "Berserk",
	DevastatingStrikes = "Coups Dévastateurs",
	KillingFrenzy = "Frénésie Sanguinaire",
	ShieldBash = "Coup de Bouclier",
	Brawny = "Musculeux",
	Stalwart = "Vigoureux",
	Taunt = "Provoquer",
	Steadfast = "Inébranlable",
	Colossus = "Mastodonte",
	ShieldExpert = "Maîtrise du Bouclier",
	NineLives = "Neufs Vies",
	BatteringRam = "Bélier",
	BattleForged = "Façonner par les Batailles",
	BagsAndBelts = "Sacs et ceintures",
	Student = "Erudit",
	Zweihander = "Maîtrise à Deux Mains",
	Pathfinder = "Éclaireur",
	FortifiedMind = "Esprit Renforcé",
	Captain = "Capitaine",
	InspiringPresence = "Présence Inspirante",
	QuickHands = "Mains Rapides",
	CripplingStrikes = "Coup Paralysant",
	Duelist = "Dueliste",
	Nimble = "Agile",
	Dodge = "Esquive",
	HoldOut = "Résilient",
	Anticipation = "Anticipation",
	SteelBrow = "Front en Acier",
	CoupDeGrace = "Executeur",
	Weaponmaster = "Maître d\'armes",
	FastAdaption = "Adaptation Rapide",
	SunderingStrikes = "Coup Fracassant",
	BattleFlow = "Au Coeur de la Bataille",
	HeadHunter = "Chasseur de Têtes",
	RallyTheTroops = "Rallier the Troupes",
	Fearsome = "Effroyable",
	Indomitable = "Invincible",
	Debilitate = "Fragiliser",
	Footwork = "Jeu de Jambes",
	Rotation = "Remplacer",
	Underdog = "Oppressé",
	Recover = "Récupérer",
	Gifted = "Talentueux",
	Adrenaline = "Adrenaline",
	Backstabber = "Poignardeur",
	LoneWolf = "Loup Solitaire",
	ReachAdvantage = "Avantage de Portée",
	Overwhelm = "Submerger",
	Relentless = "Infatigable",
	SpecBow = "Maîtrise de l\'arc",
	SpecCrossbow = "Maîtrise de l\'arbalète et des armes à Feu",
	SpecThrowing = "Maîtrise de Lancer",
	SpecAxe = "Maîtrise de la Hache",
	SpecCleaver = "Maîtrise du Hachoir",
	SpecDagger = "Maîtrise de la Dague",
	SpecSword = "Maîtrise de l\'Epée",
	SpecSpear = "Maîtrise de la Lance",
	SpecPolearm = "Maîtrise des Armes d\'Hast",
	SpecHammer = "Maîtrise du Marteau",
	SpecMace = "Maîtrise de la Masse",
	SpecFlail = "Maîtrise du Fléau"
};
gt.Const.Strings.PerkDescription <- {
	Relentless = "Ne ralentissez pas! En tout temps votre Initiative est réduite seulement de [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] de la Fatigue accumulé, au lieu 100%. De plus, utiliser la commande \'Attendre\' ne vous donnera plus de pénalité à votre initiave pour le tour suivant.",
	Rotation = "Débloque la compétence \'Remplacer\' qui permet de permuter deux personnages en ignorant la Zone de Contrôle du moment qu\'aucun des deux personnages n\'est étourdi, enraciné ou invalide.",
	Footwork = "Débloque la compétence \'Jeu de Jambes\' qui permet de de quitter une Zone de Contrôle sans déclencher un jet d\'opportunité en utilisant votre jeu de jambes habile.",
	Debilitate = "Débloque la compétence \'Fragiliser\' qui permet de paralyser la cible pour un tour, réduisant leur capacité à infliger des dégâts par [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color].",
	Indomitable = "Débloque la compétence \'Invincible\' qui permet une réduction de dégâts de [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] et une immunité contre l\'étourdissement, le repoussement ou encore la saisie pendant un tour.",
	RallyTheTroops = "Débloque la compétence \'Rallier\' qui rallie les troupes qui sont en train de fuir, et augmente le morale de tous les alliés à proximité à un niveau raisonable. Plus la détermination du personnage utilisant la compétance est élevée, plus les chances de réussite sont élevés.",
	Adrenaline = "Débloque la compétence \'Adrenaline\' qui vous place en premier au prochain tour, vous permettant d\'avoir un autre tour avant les ennemies. Sentez l\'adrénaline parcourir vos veines!",
	Fearsome = "Faites-les se disperse et s\'enfuir! Toutes les attaques qui infligent au moins 1 de dégâts déclenchent une vérification de morale pour l\'ennemi avec une pénalité égale à [color=" + this.Const.UI.Color.NegativeValue + "]20%[/color] de votre détermination, par contre, si les dégâts sont à 15 ou plus, il n\'y a pas de pénalités.",
	HeadHunter = "Visez la tête! Toucher la tête de votre cible vous garantira de toucher la tête à votre prochaine attaque. Que vous touchiez ou non votre prochaine attaque, l\'effet est réinitialisé.",
	SunderingStrikes = "L\'Efficacité contre l\'armure augmente de [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] pour n\'importe quelle arme utilisé.",
	FastAdaption = "Adaptez vous aux attaques de vos ennemies! Gagnez un stack additionnel de [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] de chance de toucher pour chaque attaque qui manque un ennemie. Le bonus est réinitialisé dès que vous touchez un ennemi.",
	Weaponmaster = "Toutes les attaques coutent [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] de Fatigue à utiliser et la condition des armes se dégrade moitié moins vite. Dancer gracieusement avec votre arme et faites que chaque coup compte. ",
	CoupDeGrace = "Inflige des dégâts additionnels de [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] contre les ennemis qui ont subis n\'importe quelle blessure comme un bras cassé.",
	SteelBrow = "Les coups à la tête n\'infligent mainteannt plus de coups critique à ce personnage, ce qui diminue par la même occasion la probabilité de subir des blessures invalidantes à la tête de manière significative.",
	Anticipation = "Quand vous êtes attaqué par des armes à distance, vous gagnez [color=" + this.Const.UI.Color.PositiveValue + "]1 + 10% de votre Défense à Distance[/color] en défense à Distance additionnel par case de distance d\'où se trouve l\'attaquant, et toujours au minimum un bonus de [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] en Défense à Distance.",
	HoldOut = "Tenez le Coup! Tous les status négatifs ont une durée prédéfini (par exemple Saignement, Charmé) ont leur durée réduite de [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] tour. Les Status qui ont leurs effets réduits au fur et à mesure du temps (par exemple Le poison Goblin) sont dans leur état le plus faible dès le début.",
	Dodge = "Trop rapide pour toi! Gagnez [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] de l\'initiative du personnage en tant que bonus de Défense (Mêlée et à Distance).",
	Nimble = "Vous êtes spécialisé en armure légère! En déviant et en esquivant agilement les attaques, transforme les coups en coups faibles. Les points de vie subis sont réduits jusqu\'à un maximum de [color=" + this.Const.UI.Color.PositiveValue + "]60%[/color], mais est diminué exponentiellement par le malus de Fatigue Maximum de l\'armure (tête et corps) au dessus de [color=" + this.Const.UI.Color.PositiveValue + "]15[/color]. Plus votre armure est légère, plus vous en bénéficierez.\n\nMusculeux n\'affecte pas ce Talent.\n\nN\'affecte pas les attaques mentales et les Effets de Status, mais peut aider à les esquiver.",
	BattleForged = "Vous êtes spécialisé en armure lourd! Les dégats d\'armure sont réduits pars un pourcentage égale à [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] du total de la valeur de l\'armure (tête et corps). Le plus lourd l\'armure et le casque, le meilleur le bénéfice.\n\nN\'affecte pas les attaques mentales et les Effets de Status, mais peut aider à les esquiver.",
	Duelist = "Devenez un avec votre arme et visez les points faibles! Quand vous avez une main libre ou avec un outil jetable (exemple Filer à jeter), vous aurez un bonus supplémentaire de [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] qui ignorera l\'armure. Ne fonctionne pas avec les armes à deux mains.",
	CripplingStrikes = "Handicaper vos ennemis! Diminue la probabilité minimum pour infliger des blessures par [color=" + this.Const.UI.Color.NegativeValue + "]33%[/color] pour les armes de mêlée et les armes à distance.",
	QuickHands = "Vous cherchiez quelque chose? Echanger un objet (sauf les boucliers) devient une action gratuite et ne consomme as de points d'action (Une fois par tour seulement).",
	Bullseye = "C\'est réglé! La pénalité de toucher un ennemi pour lequel vous n\'avez pas d\'angle de tir passe à [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] au lieu de [color=" + this.Const.UI.Color.NegativeValue + "]75%[/color] pour les armes à distance.",
	Ballistics = "The range penalty to hitchance is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] per tile.",
	Berserk = "RAAARGH! Une fois par tour, en tuant un ennemi, [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] Points d\'Action sont récupérés immédiatement. Les personnages ne peuvent regagner plus que leur nombre de points d\'action maximum.",
	BattleFlow = "Once per turn, killing an opponent reduces current fatigue by [color=" + this.Const.UI.Color.NegativeValue + "]-25%[/color] of the base maximum fatigue (before penalties due to armor are applied).",
	DevastatingStrikes = "All damage inflicted is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] for any weapon used. What could stand before you now?",
	KillingFrenzy = "Rentrez dans une Frénésie Sanguinaire! Un ennemie tué augmente tous les dégâts de [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] pour 2 tours. Ne se cumule pas, mais un nouveau tué réinitialisera le décompte.",
	ShieldBash = "The Knock Back skill now also inflicts [color=" + this.Const.UI.Color.DamageValue + "]10 - 25[/color] Damage (50% effective against armor) and [color=" + this.Const.UI.Color.DamageValue + "]10[/color] Fatigue in addition to its normal effect, and costs 10 Fatigue less to use.",
	Brawny = "La pénalité de Fatigue et d\'Initiative en portant une armure et un casque sont réduit de [color=" + this.Const.UI.Color.NegativeValue + "]30%[/color].",
	Stalwart = "Immunity against being knocked back or pulled up close. Applies to skills such as Knock Back, Hook and others that change a character\'s position.",
	Steadfast = "Getting hit by regular attacks does not cause a loss of fatigue anymore. Attacks that specifically target fatigue are unaffected.",
	Taunt = "Débloque la compétence \'Provoquer\' qui fait prendre une position offensive plutôt que défensive pour l\'ennemi ciblé, l\'ennemi cible attaquera en priorité le personnage utilisant Provoquer, ce qui permettrait de proteger une cible plus vulnérable.",
	Colossus = "Amenez-les! Les Points de vie sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color], ce qui permet de diminuer la probabilité de subir des blessures incapacitante quand vous êtes touché.",
	ShieldExpert = "Apprenez à mieux dévier les attaques de côté plutôt que de les bloquer.\n\nLe bonus de défense du bouclier est augmenté de [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]. Cela s\'applique aussi au bonus supplémentaire de Mur de Bouclier.\n\nLes dégâts qui subit le bouclier sint aussi réduits de [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] pour un minimum de 1.\n\nLa Compétence \'Repousser\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] de chance de toucher.",
	NineLives = "Une fois par bataille, en recevant un coup mortel, vous survivrez avec seulement un peu de Points de vie restant et tous les dégâts sur la durée seront soignés (ex. saignement, empoisonement). Bien sûr, le prochain coup sera probablement le dernier pour vous tuer pour de bon mais vous profiterez d\'un bonus de défense jusqu\'au prochain tour pour vous aider à survivre jusque là.",
	BatteringRam = "Immunity against being stunned.",
	BagsAndBelts = "Débloque deux emplacement de sacs supplémentaires pour vous aider à transporter vos objets favoris. Les objets pplacés dans les sacs ne donne plus de pénalités au Maximum de Fatigue, sauf pour les armes à deux mains.",
	Student = "Tout peut être appris si vous y mettez de la volonté. Gagnez un bonus additionnel de [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] à l\'experience gagné dans les batailles. Au onzième niveau de votre personnage, celui-ci gagnera un point d\'attour supplémentaire et ce Talent sera désactivé.\n\nEn jouant avec l\'origine \'Traqueur\', vous recevrez vous point de Talent au septième niveau.",
	Gifted = "La vie de mercenaire devient facile quand vous êtes naturellement talentueux. Vous gagnez instantanément un niveau pour augmenter les attributs de ce personnage (avec les meilleurs jets de stat possible), cependant vous ne gagnerez pas de point de Talent.",
	Zweihander = "Fatigue costs for all two-handed weapon skills are reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color].",
	Pathfinder = "Apprenez à vous déplacer sur les terrains accidentés. Les Points d\'Action nécessaires pour vous déplacer sur tous les types de terrains est réduite par [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] pour un minimum de 2 Points d\'Action par tuile, de plus, le coût en Fatigue est divisé par deux. Aussi, changer de hauteur ne coûte maintenant plus de Points d\'Action supplémentaires.",
	FortifiedMind = "Une volonté de fer qui ne se laissera pas détourné du bon chemin facilement. La détermination est augmenté par [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color].",
	Captain = "Nommez un sergeant sur le champ de bataille comme une extention de votre leadership pour garder tout le monde dans les rangs. Les alliés dans un rayon de 5 tuiles ou moins recevront un bonus de [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] de la détermination de ce personnage en plus de le leur, jusqu\'à un maximum de la détermination de ce personnage.\n\nNe se cumule pas; Le sergeant avec la détermination la plus élevée appliquera ce bonus.",
	InspiringPresence = "A great leader of men inspires his followers to overcome their limits. Allies start every battle at confident morale unless prohibited by character traits.",
	Underdog = "J\'y suis habitué. Le malus de défense en étant entouré d\'ennemis ne s\'applique plus à ce personnage. Si l\'ennemi possède le Talent Poignardeur l\'effet de ce Talent est annulé, et le malus de défense en étant entouré est appliqué normalement.",
	Recover = "Débloque la compétence \'Récupérer\' qui permet de se reposer pendant un tour pour réduire la fatigue accumulé par [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color].",
	Backstabber = "L\'Honneur ne vous fait pas gagner de bataille, poignarder un ennemi où ça fait mal si. Le bonus pour toucher en mêlée est augmenté par [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] pour chaque allié entourant et distrayant votre cible.",
	LoneWolf = "Je travaille mieux seul. Si vous n\'avez aucun allié dans un rayon de 3 tuiles de distance, vous gagnez un bonus de [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] en Maîtrise de Mêlée, Maîtrise à distance, Défense en Mêlée, Défense à distance et en Détermination.",
	ReachAdvantage = "Apprenez à vous servir de votre avantage d\'avoir une arme à grande portée pour empêcher les ennemis de se rapprocher pour vous frapper.\n\nChaque coup porté avec une arme de mêlée à deux main rajoute un stack du Talent Avantage de Portée ce qui augmente votre Défense de Mêlée de [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color], jusqu\'à un maximum de 5 stacks, jusqu\'au prochain tour du personnage. Une attaque qui touche plusieurs cibles peut rajouter plusieurs stacks en une fois.\n\nSi vous rangez votre arme vous perdez tous les stacks.",
	Overwhelm = "Apprenez à mieux utiliser votre Initiative en empêchant les ennemies de vous attaquer efficacement en les submergeant avec vos attques!\n\nAvec chaque attaque, touché ou manqué contre un ennemi qui agit après vous dans le tour en cours, lui inflige l\'état \'Submergé\' ce qui diminue sa Maîtrise de mêlée et à distance de [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] pour chaque tour.\n\nL\'effet se stack à chaque attaque, et peut être appliqué à plusieurs cibles en même temps en une seule attaque.",
	SpecBow = "Maîtrisez l'art de l'archerie et bombarder les ennemis de flèches depuis une certaine distance. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLa distance de vue et la distance maximale de tir avec les arcs sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	SpecCrossbow = "Maîtrisez les arbalètes et les armes à feu, et apprenez comment avoir une meilleur visée. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nEt [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] de dégâts supplémentaires infligés aves les Arbalètes ignorent l\'armure.\n\nLes Armes de poing ont maintenant besoin de [color=" + this.Const.UI.Color.NegativeValue + "]6[/color] Points d\'Action pour recharger et peuvent tirer à chaque tour et n'ont plus besoin d'attendre un tour après avoir recharger pour tirer.",
	SpecThrowing = "Maîtrisez le lancé d\'armes de lancé pour blesser ou tuer les ennemies avant même qu\'ils aient le temps de se rapprocher. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes dégâts sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]40%[/color] en attaquant à 2 tuiles de distance.\n\nLes dégâts sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] en attaquant à 3 tuiles de distance.",
	SpecAxe = "Maîtrisez le combat avec des haches ou de destruction de bouclier. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes dégâts de \'Pourfendre un Bouclier\' sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] en utilisant des haches.\n\n\'Coup Tournoyant\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance de toucher.\n\nLa Hache Danoise n\'a plus de pénalité en attaquant les cibles au contact.",
	SpecCleaver = "Maîtrisez les fendoirs pour infliger des blessures horrible. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes dégâts de saignement infligés par les fendoirs et les fouets doublés à [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] et [color=" + this.Const.UI.Color.PositiveValue + "]20[/color] par tour, respectivement.\n\nDésarmé a seulement la moitié de la pénalité pour toucher.",
	SpecDagger = "Maîtrise des dagues rapides et mortels. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Poignarder\', \'Percer\' et \'Coup Mortel\' ont un coup en Points d\'Action réduit pour permettre une attaque supplémentaire à chaque tour.",
	SpecSword = "Maîtrisez l\'art du combat à l\'épée et utilisez les erreurs de vos ennemies à votre avantage. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Riposte\' n\'a plus de malus à la probabilité de toucher.\n\n\'Entaille\' a un palier diminué de [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] pour infliger des blessures.\n\n\'Fendre\' et \'Coup d\'épée\' ont [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance en plus de toucher.",
	SpecSpear = "Maîtrisez le combat avec les lances et gardez vos ennemis à distance. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Mur de Lance\' n\'est plus désactivé dans un ennemie arrive à y rentrer. Effectivement, \'Mur de Lance\' peut toujours être utilisé et continue de faire des attaques gratuite à tous les ennemis qui tentent de rentrer dans la zone de contrôle.\n\nLe Spetum and Fourche de Guerre n\'ont plus de pénalité en attaquant les cibles au contact.",
	SpecPolearm = "Maîtrisez les armes d'hast et gardez l\'ennemi à distance. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes Armes d\'hast ont leur coup en Point d\'action réduit à [color=" + this.Const.UI.Color.NegativeValue + "]5[/color], et n\'ont plus de pénalité en attaquant les cibles au contact.",
	SpecHammer = "Maîtrisez les marteaux et combattez les ennemis en armure lourde. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Détruire l\'Armure\' et \'Destruction d\'Armure\' infligent [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] de dégâts en plus contre l\'armure.\n\n\'Fracasser\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance de toucher.\n\nLe Polehammer n\'a plus de pénalité en attaquant les cibles au contact.",
	SpecMace = "Maîtrisez les massues et soumettez vos ennemis par les coups, qu\'ils soient en armure ou non. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Assomer\', \'Renverser\' et \'Frappe Descendante\' ont [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] de chance d\'étourdir la cible si elle n\'est pas immunisé.\n\nLa Polemace n\'a plus de pénalité en attaquant les cibles au contact.",
	SpecFlail = "Maîtrisez les fléaux et contournez le bouclier de vos ennemis. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Coup à la Tête\' et \'Avalanche de Coups à la Tête\' ignorent le bonus de défense des boucliers.\n\n\'Faucher\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance de toucher."
};
gt.Const.Strings.Tooltip <- {
	World = {
		Hint_FocusParty = "Click to focus party",
		Hint_FocusLocation = "Click to focus location"
	},
	Tactical = {
		Hint_FocusCharacter = "Click to focus character",
		Hint_CannotChangeItemInCombat = "Can not be changed in combat",
		Hint_OnlyActiveCharacterCanChangeItemsInCombat = "Only the character whose turn it is right now can change items"
	}
};

