local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {
		function getArticle( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "un " : "un ";
		}

		function getArticleCapitalized( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "Un " : "Un ";
		}

	};
}

if (!("Tactical" in gt.Const.Strings))
{
	gt.Const.Strings.Tactical <- {};
}

if (!("World" in gt.Const.Strings))
{
	gt.Const.Strings.World <- {};
}

gt.Const.Strings.Quantity <- [
	"1er",
	"2ème",
	"3ème",
	"4ème",
	"5ème",
	"6ème",
	"7ème",
	"8ème",
	"9ème",
	"10ème",
	"11ème",
	"12ème",
	"13ème",
	"14ème",
	"15ème",
	"16ème",
	"17ème",
	"18ème",
	"19ème",
	"20ème"
];
gt.Const.Strings.Amount <- [
	"aucun",
	"un(e)",
	"deux",
	"trois",
	"quatre",
	"cinq",
	"six",
	"sept",
	"huit",
	"neuf",
	"dix",
	"onze",
	"douze",
	"treize",
	"quatorze",
	"quinze",
	"seize",
	"dix-sept",
	"dix-huit",
	"dix-neuf",
	"vingt",
	"vingt et un",
	"vingt-deux",
	"vingt-trois",
	"vingt-quatre",
	"vingt-cinq",
	"vingt-six",
	"vingt-sept",
	"vingt-huit",
	"vingt-neuf",
	"trente"
];
gt.Const.Strings.AmountC <- [
	"Aucun",
	"Un(e)",
	"Deux",
	"Trois",
	"Quatre",
	"Cinq",
	"Six",
	"Sept",
	"Huit",
	"Neuf",
	"Dix",
	"Onze",
	"Douze",
	"Treize",
	"Quatorze",
	"Quinze",
	"Seize",
	"Dix-sept",
	"Dix-huit",
	"Dix-neuf",
	"Vingt",
	"Vingt et un",
	"Vingt-deux",
	"Vingt-trois",
	"Vingt-quatre",
	"Vingt-cinq",
	"Vingt-six",
	"Vingt-sept",
	"Vingt-huit",
	"Vingt-neuf",
	"Trente"
];
gt.Const.Strings.Difficulty <- [
	"Débutant",
	"Vétéran",
	"Expert"
];
gt.Const.Strings.EntityName <- [
	"Nécromanciens",
	"Revenant",
	"Revenant en armure",
	"Héro déchu",
	"Esprit vengeur",
	"Auxiliaire antique",
	"Légionnaire antique",
	"Garde d\'honneur antique",
	"Prêtre antique",
	"Le Conquérant",
	"Necrosavant",
	"Esprit",
	"Nachzehrer",
	"Jeune orc",
	"Berserker orc",
	"Guerrier orc",
	"Seigneur de guerre orc",
	"Milicien",
	"Tireur d\'élite milicien",
	"Vétéran milicien",
	"Capitaine de milice",
	"Chasseur de primes",
	"Paysan",
	"Employé de caravane",
	"Garde de caravane",
	"Charette de caravane",
	"Fantassins",
	"Zweihander",
	"Vougier",
	"Arbalétrier",
	"Porte-étendard",
	"Sergent",
	"Chevalier",
	"Âne",
	"Brigand",
	"Braconnier",
	"Tireur d\'élite brigand",
	"Pillard brigand",
	"Chef brigand",
	"Gobelin embusqué",
	"Tirailleur gobelin",
	"Surveillant gobelin",
	"Chaman gobelin",
	"Chevaucheur de loup gobelin",
	"Loup",
	"Chien de guerre",
	"Chien de guerre blindé",
	"Mercenaire",
	"Mercenaire",
	"Maître d\'armes",
	"Chevalier errant",
	"Maître archer",
	"Catapulte peau verte",
	"Cultiste",
	"Loup-garou",
	"Lindwurm",
	"Unhold",
	"Unhold",
	"Unhold",
	"Webknecht",
	"Oeufs de Webknecht",
	"Alp",
	"Hexe",
	"Schrat",
	"Sapling",
	"Homme sauvage",
	"Kraken",
	"Irrlicht",
	"Traître déchu",
	"Nightmare",
	"Serf barbare",
	"Saccageur barbare",
	"Élu barbare",
	"Tambour barbare",
	"Maître des bêtes barbare",
	"Unhold en armure",
	"Unhold en armure",
	"Roi barbare",
	"Chien de chasse (de guerre)",
	"Le Ijirok",
	"Barbare aliéné",
	"Serpent",
	"Ifrit",
	"Hyène",
	"Conscrit",
	"Artilleur",
	"Officier",
	"Ingénieur",
	"Assassin",
	"Endetté",
	"Gladiateur",
	"Mortier",
	"Coupe-gorge nomade",
	"Hors-la-loi nomade",
	"Frondeur nomade",
	"Archer nomade",
	"Chef nomade",
	"Traqueur du désert",
	"Bourreau nomade",
	"Danseur de lames",
	"Citoyen",
	"Le Gardien du Savoir (Lorekeeper)",
	"Apparition du Gardien du Savoir",
	"Phylactères",
	"Chasseur de trésors (perdu ? todo)",
	"Crâne hurlant",
	"Oathbringer"
];
gt.Const.Strings.EntityNamePlural <- [
	"Nécromanciens",
	"Revenants",
	"Revenants en armure",
	"Héros déchus",
	"Esprits vengeurs",
	"Auxiliaires antiques",
	"Légionnaires antiques",
	"Gardes d\'honneur antiques",
	"Prêtres antiques",
	"le Conquérant",
	"Necrosavants",
	"Esprits",
	"Nachzehrers",
	"Jeunes orcs",
	"Berserkers orcs",
	"Guerriers orcs",
	"Seigneurs de guerre orcs",
	"Milicien",
	"Tireurs d\'élite miliciens",
	"Vétérans miliciens",
	"Capitaines de milice",
	"Chasseurs de primes",
	"Paysans",
	"Employés de caravane",
	"Gardes de caravane",
	"Chariots de caravane",
	"Fantassins",
	"Zweihanders",
	"Vougiers",
	"Arbalétriers",
	"Porte-étendards",
	"Sergents",
	"Chevaliers",
	"Ânes",
	"Brigands",
	"Braconniers",
	"Tireurs d\'élite brigands",
	"Pillards brigands",
	"Chefs brigands",
	"Gobelins embusqués",
	"Tirailleurs gobelins",
	"Surveillants gobelins",
	"Chamans gobelins",
	"Chevaucheurs de loup gobelins",
	"Loups",
	"Chiens de guerre",
	"Chiens de guerre blindés",
	"Mercenaires",
	"Mercenaires",
	"Maîtres d\'armes",
	"Chevaliers errants",
	"Maîtres archers",
	"Capatapultes peau verte",
	"Cultistes",
	"Loups-garous",
	"Lindwurms",
	"Unholds",
	"Unholds",
	"Unholds",
	"Webknechts",
	"oeufs de Webknecht",
	"Alps",
	"Hexen",
	"Schrats",
	"Saplings",
	"Hommes sauvages",
	"Kraken",
	"Irrlicht",
	"Traîtres déchus",
	"Nightmares",
	"Serfs barbares",
	"Saccageurs barbares",
	"Élus barbares",
	"Tambours barbares",
	"Maîtres des bêtes barbares",
	"Unholds en armure",
	"Unholds en armure",
	"Rois barbares",
	"Chiens de chasse (de guerre)",
	"Bêtes de l\'hiver",
	"Barbares aliénés",
	"Serpents",
	"Ifrits",
	"Hyènes",
	"Conscrits",
	"Artilleurs",
	"Officiers",
	"Ingenieurs",
	"Assassins",
	"Endettés",
	"Gladiateurs",
	"Mortiers",
	"Coupe-gorges nomades",
	"Hors-la-loi nomades",
	"Frondeurs nomades",
	"Archers nomades",
	"Chefs nomades",
	"Traqueurs du désert",
	"Bourreaux nomades",
	"Danseur de lames",
	"Citoyens",
	"Le Gardien du Savoir(Lorekeeper)",
	"Apparition du Gardien du Savoir",
	"Phylactères",
	"Chasseurs de trésors (perdus ? todo)",
	"Crânes hurlants",
	"Oathbringers"
];
gt.Const.Strings.Tactical.EntityName <- {
	Boulder = "Rocher",
	Ruin = "Ruine",
	Shrubbery = "Arbuste",
	Tree = "Arbre",
	Brush = "Buisson",
	Cartwheel = "Vieille roue",
	RuinedPillar = "Pilier en ruine",
	Cart = "Chariot de caravane",
	Donkey = "Âne",
	Plant = "Plante"
};
gt.Const.Strings.Tactical.EntityDescription <- {
	Boulder = "Un gros rocher de pierre. Bloque le mouvement et la ligne de mire.",
	Ruin = "Des ruines d\'un autre age.",
	Shrubbery = "Arbuste très dense qui bloque le mouvement et la ligne de mire.",
	Tree = "Un grand arbre avec un tronc massif.",
	TreeSwamp = "Cet arbre est pourri et mort depuis longtemps.",
	TreeTrunk = "Un tronc d\'arbre à moitié couvert d\'eau sale.",
	Brush = "Arbuste très dense qui bloque le mouvement et la ligne de mire.",
	Cartwheel = "La vieille roue cassée d\'un char à bœufs.",
	RuinedPillar = "TODO",
	Cart = "Une charette pleine de marchandises commerciales.",
	Donkey = "Un âne utilisé pour tirer des charrettes lourdes.",
	Plant = "Une plante exotique qui bloque le mouvement et la ligne de mire."
};
gt.Const.Strings.FootprintsType <- [
	"",
	"Des soldats du nord",
	"Gilded soldiers",
	"Une caravane",
	"Des paysans",
	"Une milice",
	"Réfugiers",
	"Des brigands",
	"Des mort-vivants",
	"Des orcs",
	"Gobelins",
	"Barbares",
	"Nomades",
	"Des loups-garous",
	"Nachzehrers",
	"Des hyènes",
	"Des serpents",
	"Webknechts",
	"Unholds",
	"Alps",
	"Hexen",
	"Des Gnomes",
	"Un kraken",
	"Des Ifrits",
	"Lindwurms",
	"Des mercenaires"
];
gt.Const.Strings.ShipNames <- [
	"Summer Daze",
	"Joyeuse Brume",
	"Hurlement de la Mer",
	"Secret de Corail",
	"Baie de Sable",
	"Dame de la Mer",
	"Solitaire",
	"Brynhildr",
	"Mathilda",
	"Comète",
	"Tétrarque",
	"Lofjord",
	"Vent d\'Automne",
	"Poundmaker",
	"Brakel",
	"Sept Étoiles",
	"Sombre Présage",
	"Concorde",
	"Albatros",
	"Cheval d\'Or",
	"Nymphe des Mers",
	"Destinée Tordue",
	"Prime du Roi",
	"Moine Chauve",
	"Soleil d\'Or",
	"Vanité",
	"L\'Effronté",
	"Griffe du Tigre",
	"Sycomore",
	"Noble Coursier",
	"Morne Lune",
	"Homme du Clan",
	"Whale\'s Voyage",
	"Rapide Correspondance",
	"Mouche Noire",
	"Ejnar Erikson",
	"Lindwurm",
	"Suprême",
	"Griffon",
	"Axford",
	"Bertha",
	"Mouette",
	"Belzebub"
];
gt.Const.Strings.MercenaryCompanyNames <- [
	"Corbeaux de Fer",
	"Ordre Dorée",
	"Épées du Sud",
	"Loups de la Morne Forêt",
	"Boucliers Noirs",
	"Compagnie Couronne de Fer",
	"Épées de Radobrecht",
	"Flèches Sifflantes",
	"Sanglier d\'Azur",
	"Crocs et Pièces",
	"Légion Rouge",
	"Meutes Affamés",
	"Dagues Cramoisies",
	"Compagnie de l\'Issue du Roi",
	"Compagnie Noire",
	"Seconds Fils",
	"Confrérie de Walther",
	"Faiseur-de-Rancunes",
	"Ours de Bernhard",
	"Griffe d\'Argent",
	"Fraternité de Fer",
	"Compagnie Fléau-des-Orcs",
	"Alliance de Fer",
	"Tiers Intact",
	"Chiens de Guerre",
	"Légion de Falkenberg",
	"Hommes Libres",
	"Seigneurs de Guerre",
	"Compagnie du Nord",
	"Forsaken Returned",
	"Compagnie Blanche",
	"Faiseurs de Veuves",
	"Compagnie Coeurs de Glace",
	"Compagnie du Soleil Brûlant",
	"Rares Élus",
	"Hommes Morts",
	"Têtes-de-Bronze",
	"Piques de Markland",
	"Garde-Marteau",
	"Preneurs-de-Couronne",
	"Lances Touchargentées",
	"Pacte de Fer",
	"Sang-Liés",
	"Rempart",
	"Marche de l\'Aube",
	"Fils de l\'Hiver",
	"Compagnie de la Maison de la River",
	"Compagnie de la Comète Enflammée",
	"Grande Compagnie",
	"Justes Ravageurs",
	"Brigade des Délaissés",
	"Élus de Bataille",
	"Porteurs de Paix",
	"Boucliers de la Nuit",
	"Corniauds",
	"Gardes-Os",
	"Légion Perdue"
];
gt.Const.Strings.NobleHouseNames <- [
	"Grimmet",
	"Weilbourg",
	"Armsberg",
	"Gota",
	"Ferpierre",
	"Murgris",
	"Prisecorbac",
	"Vindété",
	"Halledhiver",
	"Gloria",
	"Noblerègne",
	"Pérovingie",
	"Eiglof",
	"Berengar",
	"Gunbald",
	"Goswin",
	"Adelheim",
	"Ammondt",
	"Bartholin",
	"Eberlin",
	"Folsach",
	"Hedin",
	"Corne",
	"Niedergard",
	"Rosenving",
	"Thurah",
	"Glacenée",
	"Krieger",
	"Murpierre",
	"Harkon",
	"Osten"
];
gt.Const.Strings.CityStateNames <- [
	"Dahab",
	"Kabira",
	"Ras Sanan",
	"Tanwir",
	"Azim Shab",
	"Tarwa",
	"Hakim Al Ramal",
	"Karrakan",
	"Al-Hazred",
	"Al-Hazif",
	"Quadim",
	"Hikma",
	"El-Hadet",
	"Al-Anwar"
];
gt.Const.Strings.CityStateTitles <- [
	"Cité État de",
	"Cité de",
	"Protectorat de",
	"Royaume de",
	"Grande ville de",
	"Ville Libre de",
	"Ville Sainte de"
];
gt.Const.Strings.BusinessReputation <- [
	"Perfide",
	"Incompétent",
	"Non fiable",
	"Inconnu",
	"Reconnu",
	"Fiable",
	"Compétent",
	"Professionnel",
	"Réputé",
	"Fameux",
	"Génial",
	"Glorieux",
	"Fabuleux",
	"Légendaire",
	"Invincible",
	"Immortel"
];
gt.Const.Strings.MoralReputation <- [
	"Redouté",
	"Cruel",
	"Sans Merci",
	"Malfamé",
	"Neutre",
	"Neutre",
	"Gentil",
	"Bon",
	"Chevaleresque",
	"Saint"
];
gt.Const.Strings.Relations <- [
	"Hostile",
	"Menaçant",
	"Inamical",
	"Froid",
	"Neutre",
	"Neutre",
	"Ouvert",
	"Amical",
	"Très amical",
	"Allié"
];
gt.Const.Strings.Tactical.TerrainName <- [
	"Aucun",
	"Route sale",
	"Route d\'argile",
	"Route pavée",
	"Prairie",
	"Saleté",
	"Forêt",
	"Terre boueuse",
	"Herbe humide",
	"Eau trouble",
	"Steppe",
	"Steppe sèche",
	"Toundra",
	"Neige",
	"Neige légère",
	"Pierre",
	"Pierre",
	"Sable",
	"Eau peu profonde"
];
gt.Const.Strings.Tactical.TerrainDescription <- [
	"Aucun",
	"Un chemin de terre tracé par les humains et les animaux.",
	"Une route primitive constituée d\'argile damée.",
	"Une route pavée utilisée pour les transports et les gros véhicules.",
	"Herbe courte sur sol plat et solide.",
	"Terre nue et plate avec peu de végétation.",
	"Sol forestier recouvert d\'une couche de mousse épaisse et douce.",
	"Terre sombre et boueuse.",
	"Sol principalement ferme recouvert d\'herbe haute et molle.",
	"Eau peu profonde et trouble couvrant un sol meuble et boueux.",
	"Sol plat et ferme recouvert d\'herbes sèches et ratatinées.",
	"Des plaques de terre dures complètement desséchées par le soleil et la chaleur.",
	"Sol plat et aride couvert d\'herbes rugueuses et de mauvaises herbes.",
	"Sol gelé recouvert d\'une épaisse couche de neige.",
	"Sol gelé recouvert d\'une légère couche de neige.",
	"Sol en pierre lisse offrant une bonne assise.",
	"Sol en pierre brute.",
	"Sable brûlant du désert.",
	"Eau claire et peu profonde."
];
gt.Const.Strings.UI <- {
	Introduction = "Vous baignez dans l\'air frais du matin. Alors que le soleil se lève lentement, ainsi commence un nouveau chapitre de votre vie. Après des années à user votre épée pour un maigre salaire, vous avez économisé suffisamment de couronnes pour démarrer votre propre entreprise de mercenaires. Avec vous êtes %allbrothers% avec qui vous avez combattu côte à côte dans le Mur de boucliers. Vous êtes désormais leur commandant, le chef de %companyname%. \n\nAu fur et à mesure que vous parcourez les terres, vous devez engager de nouveaux hommes dans les villages et les villes pour remplir vos rangs. Beaucoup de ceux qui offrent leurs services n\'auront jamais pris une vraie arme auparavant. Peut-être qu\'ils sont désespérés, peut-être qu\'ils sont avides de butin de guerre rapide. La plupart d\'entre eux mourront sur le champ de bataille. Mais ne vous découragez pas. Telle est la vie de mercenaire, et le prochain village aura toujours de nouveaux hommes à la recherche d\'un nouveau départ dans la vie.\n\nLes terres sont dangereuses ces temps-ci. Les voleurs et les pillards sont en embuscade au bord des routes, les bêtes sauvages errent dans les forêts sombres et les tribus orques sont agitées dans les marais à l\'est. Il y a même des rumeurs selon lesquelles la magie noire serait à l\'œuvre, les morts se relevant de leurs tombes et marchant à nouveau. Il existe de nombreuses opportunités de gagner beaucoup d\'argent, que ce soit en acceptant des contrats que vous pouvez trouver dans les villages, les villes et les forteresses de tout le pays, ou en vous aventurant seul pour explorer et faire des raids.\n\nVos hommes se tournent vers vous pour les guider. Ils vivent et meurent pour %companyname% maintenant.\n\n[color=#bd9d71]AVIS D\'ACCÈS ANTICIPÉ : Cette version est toujours en cours de travail et ne représente pas la qualité finale du produit. Les fonctionnalités peuvent être incomplètes ou manquantes, l\'interface utilisateur n\'a pas encore de peau, il y aura des bugs, et l\'équilibrage et la progression de l\'économie, des ressources et des ennemis peuvent nécessiter des ajustements et peuvent être parfois trop difficiles ou faciles. De nombreux contenus supplémentaires seront ajoutés au cours de l\'accès anticipé, notamment plus d\'ennemis, d\'objets, de contrats, de types de terrain, de lieux uniques, d\'événements de l\'histoire et d\'autres fonctionnalités.[/color]",
	FleeDialogueConsequences = "Parfois, il vaut mieux faire une retraite tactique pour vivre et combattre un autre jour. Les hommes tenteront d\'atteindre les bords de la carte par eux-mêmes, puis se retireront en toute sécurité. Cependant, les ennemis peuvent les rattraper et toute personne actuellement engagée peut ne pas être en mesure de s\'en sortir indemne ou même vivante.",
	RetreatDialogueConsequences = "Les ennemis sont défaits et fatigués. Les quelques survivants s\'éparpillent dans toutes les directions. Allez-vous les traquer pour réclamer leurs têtes et leurs biens, ou déclarer la bataille gagnée ?"
};
gt.Const.Strings.AlpStateName <- [
	"",
	"Existant partiellement dans les rêves",
	"Existant partiellement dans les rêves",
	"Existant principalement dans les rêves",
	"Existant principalement dans les rêves"
];
gt.Const.Strings.BodyPartName <- [
	"corps",
	"tête"
];
gt.Const.Strings.ItemSlotName <- [
	"Corps",
	"Tête",
	"Main Dominante",
	"Main Non-Dominante",
	"Accessoire",
	"Sac"
];
gt.Const.Strings.World.TimeOfDay <- [
	"Aube",
	"Matin",
	"Midi",
	"Après-Midi",
	"Soir",
	"Crépuscule",
	"Nuit",
	"Aube"
];
gt.Const.Strings.Direction <- [
	"nord",
	"nord-est",
	"sud-est",
	"sud",
	"sud-ouest",
	"nord-ouest",
	"<Indéfini>"
];
gt.Const.Strings.Direction8 <- [
	"au nord",
	"au nord-est",
	"à l\'est",
	"au sud-est",
	"au sud",
	"au sud-ouest",
	"à l\'ouest",
	"au nord-ouest"
];
gt.Const.Strings.Terrain <- [
	"",
	"dans l\'océan",
	"sur les plaines",
	"dans les marais",
	"sur les collines",
	"dans la forêt",
	"dans la forêt",
	"dans la forêt",
	"dans la forêt",
	"dans les montagnes",
	"",
	"",
	"dans la neige",
	"in the wastelands",
	"dans la toundra",
	"dans les steppes",
	"sur la côte",
	"dans le désert",
	"dans les zones humides"
];
gt.Const.Strings.TerrainAlternative <- [
	"",
	"",
	"dans les plaines",
	"dans le marais",
	"sur une colline",
	"dans la forêt",
	"dans la forêt",
	"dans la forêt",
	"dans la forêt",
	"sur une montagne",
	"dans les plaines",
	"dans les plaines",
	"dans la neige",
	"",
	"dans la toundra",
	"dans les steppes",
	"",
	"dans le désert",
	"dans des zones humides"
];
gt.Const.Strings.TerrainShort <- [
	"",
	"baie",
	"plaines",
	"marais",
	"collines",
	"forêt",
	"forêt",
	"forêt",
	"forêt",
	"montagne",
	"",
	"",
	"neige",
	"zones humides",
	"toundra",
	"steppe",
	"côte",
	"",
	"désert",
	"collines",
	"zones humides"
];
gt.Const.Strings.TerrainRegionNames <- [
	[],
	[
		"Mer Tempetueuse",
		"Refuge du Kraken",
		"Mer des Blancs Chevaux",
		"Mer des Mille Mouettes",
		"Profondes Abysses",
		"Ocean Pluvieux",
		"Libre Ocean",
		"Ocean Tempete",
		"Mer du Tonnerre",
		"Grande Mer",
		"Mer des Flots",
		"Mer de Perles",
		"Mer Hurlante",
		"Mer Cruelle",
		"Ocean des Marees Cambrees",
		"Mer des Flots Murmurants",
		"Mer aux Douces Clapotis",
		"Mer Verte",
		"Mer des Marées Changeantes",
		"Océan des Lamentations",
		"Bas-Fonds Ecumeux",
		"Ocean de la Maree Trouble",
		"Etendue Chatoyante",
		"Etendue Azuree",
		"Le Golfe Déchaine",
		"Les profondeurs Chatoyantes"
	],
	[
		"Vendland",
		"Champs Veronique",
		"Plaineterre",
		"Vinland",
		"Basses-Terres",
		"Terres des Vents",
		"Large Garde",
		"Domaine Glaucious",
		"Riches Prairies",
		"Markland",
		"Comte des Rapides Nuees",
		"Clairevallee",
		"Chaine des Prestes-Pas",
		"Aubaine du Vagabond",
		"Comte de Vallon",
		"Ridland",
		"Vertsillon",
		"Hogfolk",
		"Durum",
		"Gue des Bas-fonds",
		"Deux-Domaines",
		"Moulin du Roi",
		"Arpent-Hache",
		"Glendale",
		"Sillonbarbe",
		"Kindon",
		"Simplevert",
		"Crête d\'Elan",
		"Altmark",
		"Neumark",
		"Etendue Claire",
		"Centrepoint",
		"Prairies",
		"Vallee des Mousses",
		"Vaste-Arpent",
		"Fleur du Sud",
		"Terre d\'Aurore",
		"Pres du Bois de Chêne",
		"Arpent du Vent du Sud",
		"Pre de la Crique",
		"Champs de Saules",
		"Patures Bellevue",
		"Vallee du Rossignol",
		"Champs du Sauge-argentee",
		"Étendue du Chant de Coeur"
	],
	[
		"Marecages Noirs",
		"Etangs mortels",
		"Champs de Goudron",
		"Plitourbe",
		"Tourbiere Suffocante",
		"Etranges Marecages",
		"Marais Noir",
		"Souille Poisseuse",
		"Bourbier Redoute",
		"Terres des Marais Troubles",
		"Mortun",
		"Noir-Eventail",
		"Tourbiere du Gibier",
		"Vautrebouse",
		"Marais des Chiens",
		"Marais de Shipreath",
		"Terres Maudites",
		"Basses-Sombres",
		"Les Roseaux",
		"Cale-Grenouille",
		"Bosquet Araignee",
		"Trepas du Duc",
		"Fosses Sans-Fond",
		"Marais Souffle-Poison",
		"Bosquet Leches-Grenouille",
		"Fondmort",
		"Les Terres-Humides",
		"Les Marais",
		"Boue Noire",
		"Lande Desolee",
		"Polder des Fumees Noires",
		"Polder Sans-Fin",
		"Bassin de Tourbe",
		"Clairières du Riverland",
		"Entrailles du Sud",
		"Marais Azure",
		"Tourbiere des Mille Miroirs",
		"L\'Etroit Bourbier",
		"Clairieres de la decrepitude",
		"Zones humides des Cendres",
		"Tourbiere Sauvage",
		"Bourbier du Murmure",
		"Eaux Interdites",
		"Lande Terrifiante"
	],
	[
		"Tumulus Pli d\'Os",
		"Collines de la Hache du Chevalier",
		"Monticule Souffle-Cranes",
		"Tertres Antiques",
		"Collines Vieuverrou",
		"Les Monticules",
		"Le Bercail du Savoir",
		"Anciens Cairns",
		"Collines Fredonnantes",
		"Roches Tranchantes",
		"Tumulus Brumeux",
		"Rochecollines",
		"Tertres Pierriers",
		"Buttes-au-Lit",
		"Collines Fantomes",
		"Monticules de la Banshee",
		"Bosses de Galets",
		"Collines Gardes-Terre",
		"Cailloux du Geant",
		"Collines du Serpent Enfoui",
		"Collines Glisse-Crane",
		"Collines de Rouillegrotte",
		"Collines du Mont-Sorciere",
		"Collines Genevrier",
		"Tertres de la Blanche-Chèvre",
		"Barum",
		"The Reach",
		"Collines aux Murmures",
		"Les Collines de Bronze",
		"Coteau du Comte de Saule",
		"Les Collines Ecarlates",
		"Pentes du Geant",
		"Les Collines Lugubres",
		"Les Collines Effondrees"
	],
	[
		"Foret Desolee",
		"Bois Desastre",
		"Bois Lugubre",
		"Foret Sombre",
		"Foret des Canailles",
		"Bois Sanglier",
		"Repos du Brigand",
		"Vallecharde",
		"Bois de l\'Araignee",
		"Fourre des Tiques",
		"Bosquet des Druides",
		"Bois de la Branche Fragile",
		"Foyer du Loup Blanc",
		"Prise du Corbeau",
		"Bosquet d\'Aiguilles",
		"Fourre Bruissant",
		"Bois de Pins Moussus",
		"Nid-de-Corbeau",
		"Foret Noire",
		"Bois des Rodeurs",
		"Bois Morose",
		"Loup-Bois",
		"Bois Noirs",
		"Bois des Murmures",
		"Sombre Epine Sauvage",
		"Fourre du Herisson",
		"Abri Brumeux",
		"Vallebordure",
		"Temple Grove",
		"Bois Misereux",
		"Bois des Anciens",
		"Profond Abri",
		"Bois Ara Macao",
		"Sort-Foret"
	],
	[],
	[
		"Foret Seculaire",
		"Repos du Forestier",
		"Vallee des Cerfs",
		"Vieux-Bois",
		"Rampants",
		"Bosquet Ironoak",
		"Bosque du Chasseur",
		"Domaine Royal",
		"Bois Sylvestre",
		"Bois du Renard et Lievre",
		"Foret Rameaux Serpentins",
		"Sillon Ramures",
		"Vieille Foret",
		"Foret de Boivert",
		"Bois Mousseux",
		"Bois Brumeux",
		"La Mer d\'Arbres",
		"Terres-Bois",
		"Bosquet Chuchotant",
		"Bois du Grand-Lievre",
		"Bois Chataignier",
		"Terrier du Serpent",
		"Foret Bois-Noir",
		"Bois Orage",
		"Fourre Bruissant",
		"Bois Malfaisant",
		"Terres-Bois du Gris-Crapaud",
		"Terres Boisees des Arbres-Marcheurs",
		"Bois Denteles",
		"Terres du Cerf",
		"Foret du Chene Sacre",
		"Bois de Sureau",
		"Bosquet des Ormes",
		"Bois de la Taupe Noire",
		"Bois-Roseau",
		"Source-Bois",
		"Bois Eternels"
	],
	[
		"Bois du Ver Rouge",
		"Bois Ardents",
		"Bois Embrases",
		"Braise-Bois",
		"Bosquet Vivant",
		"Foret de l\'Antre du Renard",
		"Somerhurst",
		"Fireander",
		"Bloodcut Growth",
		"Burnend",
		"Rustdroop",
		"Bois Sanglants",
		"Foret Embrasee",
		"Bois Vermillion",
		"Foret Carmine",
		"Bois Auburn",
		"Rougebois ",
		"Terrier du Blaireau",
		"Foresterie Bouleau",
		"Foret Eaubois",
		"Bois-Bucher",
		"Frapperacine Sauvage",
		"Bosquet de Boistourbière",
		"Etendue Jaunefeuilles",
		"Bois Fleursang",
		"Foret Rouges-Ecorces",
		"Bosquet Rochefeu"
	],
	[
		"Epine Dorsale du Monde",
		"Dos des Geants Dormants",
		"Fleches Dentelees",
		"Mur des Dieux",
		"Rocs Redoutables",
		"Crete Rocheuse",
		"Sommet Dechiquete",
		"Crete d\'Argent",
		"Sommet Brumeux",
		"Montagnes de Fer",
		"Cornes-de-Chevre",
		"Dents-du-dragon",
		"Haute-Tour",
		"Vol d\'Aigle",
		"Sombre-Toit",
		"Pic Louvet",
		"Corne-Terreur",
		"Bec-des-Corbeaux",
		"Mont Cloison",
		"Rempart",
		"Mottetes",
		"Pentes-des-Sommets",
		"Chute du Heros",
		"Breches Beantes",
		"Epaules-de-Mammouth",
		"Hauts Pics-Enfles",
		"Calotte Nue",
		"Crete-Nuage",
		"Montagnes Brumes-Eternelles",
		"Mont-Massacre",
		"La Faille",
		"Les Pics du Tonnerre",
		"Hauts Décrepis",
		"Les Hauteurs Scintillantes",
		"Montee Deserte",
		"La Vaste Ascension",
		"Pics Clair-de-lune",
		"Le Pinacle Cendre",
		"Les Pics Nus",
		"Les Montagnes de l\'Ombre",
		"Pics Crassepierre",
		"Soufre Epaules",
		"Pics de Fer"
	],
	[],
	[],
	[
		"Friche Blanche",
		"Plaines Gelées",
		"Mer de Neige",
		"Desert Blanc",
		"Plaines Argentees",
		"Friches Hurlantes",
		"Plateaux Argentes",
		"Hiver-Eternel",
		"Nord Glace",
		"Bord du Monde",
		"Froide-Fin",
		"Wintermore",
		"Glacemarque",
		"Vent-Pique",
		"Iceblade Dale",
		"Silversand Hold",
		"Frostfold",
		"Icehenge",
		"Frozen Burrows",
		"Aurora Flats",
		"Frostfinger\'s Realm",
		"Nevermelting Hold",
		"The Pale Expanse",
		"Desert of Mirrors",
		"The Ghostly Plains",
		"Chillwind Flatlands",
		"The Glazed Valley",
		"The Howling Desert",
		"The Powder Plains",
		"Snowbank"
	],
	[],
	[
		"Northmark",
		"Tablelands",
		"Scragglands",
		"Norshire",
		"Barescrub",
		"Forefathers\' Highlands",
		"Skyreach",
		"Clan\'s Claim",
		"Rugged Flats",
		"Northern Clanlands",
		"Northern Reaches",
		"Ragwilds",
		"Landes",
		"Ragnar\'s Range",
		"Pagan Heathland",
		"Ruffmuir",
		"Windlands",
		"Angbride",
		"Baleford",
		"Bleakwolds",
		"Nordlands",
		"Glenmore Barrows",
		"Woldwich",
		"Kinmere",
		"Northurst",
		"Norenford",
		"Holmburn",
		"The Dreary Barrens"
	],
	[
		"Scrublands",
		"Drylands",
		"Torched Plains",
		"Red Lowlands",
		"Scorching Shire",
		"Golden Valley",
		"Southern Steppe",
		"Southmark",
		"The Scald",
		"Bleached Bone Dale",
		"Droughtshire",
		"Sunpan",
		"The Dryweeds",
		"Thornvale",
		"Bronze Flats",
		"Dire Hold",
		"Parcheim",
		"Smallriver Hold",
		"Razorshrub",
		"Gnarlheim",
		"Gritstone",
		"Suderos",
		"Suderland",
		"Solsweald",
		"Rustyblade Mesa",
		"Muskena",
		"Solstein",
		"Southwatch",
		"Sunreach",
		"Sandshear",
		"Skauna",
		"Caskain",
		"Maraman",
		"Jundland",
		"The Borderlands"
	],
	[],
	[
		"Silver Sands",
		"Dead Sands",
		"Golden Flats",
		"Timeless Sands",
		"Glittering Sands",
		"Scorching Desert",
		"The Emptiness",
		"The Burning Barrens",
		"Southern Sands",
		"Dusty Desert",
		"Sea of Sand",
		"Land of the Sun",
		"The Great Desert",
		"Neverending Sands",
		"Southern Reach",
		"Mumbling Sands",
		"Whispering Sands",
		"Shifting Sands",
		"Moaning Sands",
		"Sparkling Sands",
		"Glistening Flats",
		"Dry Wastes"
	],
	[
		"L\'Oasis Perdue",
		"Verts Bas-Fonds",
		"Bassin Émeraude",
		"Perle du Sud",
		"Fertiles Bas-fonds",
		"Sources de Vie",
		"Don de Dieu",
		"Salut du Prophète",
		"Les Terres Humides"
	]
];
gt.Const.Strings.Distance <- [
	"près",
	"pas loin",
	"pas très loin",
	"une certaine distance",
	"loin",
	"très loin"
];
gt.Const.Strings.PartyStrength <- [
	"Ridicule",
	"Faible",
	"Moyen",
	"Fort",
	"Dangereux",
	"Mortel",
	"Invincible"
];
gt.Const.Strings.EngageEnemyNumbers <- [
	"Un peu de",
	"Quelques",
	"De nombreux",
	"Beaucoup de",
	"Une multitude de"
];
gt.Const.Strings.InventoryHeader <- [
	"Âne",
	"Charette",
	"Chariot",
	"Grand Chariot"
];
gt.Const.Strings.InventoryUpgradeHeader <- [
	"Acheter une Charette",
	"Acheter un Chariot",
	"Acheter un grand Chariot"
];
gt.Const.Strings.InventoryUpgradeText <- [
	"acheter une charette",
	"acheter un chariot",
	"acheter un grand chariot"
];
gt.Const.Strings.InventoryUpgradeCosts <- [
	"5,000",
	"10,000",
	"20,000"
];
gt.Const.Strings.PerkName <- {
	Bullseye = "Entre les Deux Yeux",
	Ballistics = "Ballistique",
	Berserk = "Berserk",
	DevastatingStrikes = "Coups Dévastateurs",
	KillingFrenzy = "Frénésie Sanguinaire",
	ShieldBash = "Coup de Bouclier",
	Brawny = "Musculeux",
	Stalwart = "Vigoureux",
	Taunt = "Provoquer",
	Steadfast = "Inébranlable",
	Colossus = "Mastodonte",
	ShieldExpert = "Maîtrise du Bouclier",
	NineLives = "Neufs Vies",
	BatteringRam = "Bélier",
	BattleForged = "Façonné par les Batailles",
	BagsAndBelts = "Sacs et ceintures",
	Student = "Erudit",
	Zweihander = "Maîtrise à Deux Mains",
	Pathfinder = "Éclaireur",
	FortifiedMind = "Esprit Renforcé",
	Captain = "Capitaine",
	InspiringPresence = "Présence Inspirante",
	QuickHands = "Mains Rapides",
	CripplingStrikes = "Coup Paralysant",
	Duelist = "Dueliste",
	Nimble = "Agile",
	Dodge = "Esquive",
	HoldOut = "Résilient",
	Anticipation = "Anticipation",
	SteelBrow = "Front en Acier",
	CoupDeGrace = "Executeur",
	Weaponmaster = "Maître d\'armes",
	FastAdaption = "Adaptation Rapide",
	SunderingStrikes = "Coup Fracassant",
	BattleFlow = "Au Coeur de la Bataille",
	HeadHunter = "Chasseur de Têtes",
	RallyTheTroops = "Rallier les Troupes",
	Fearsome = "Effroyable",
	Indomitable = "Invincible",
	Debilitate = "Fragiliser",
	Footwork = "Jeu de Jambes",
	Rotation = "Remplacer",
	Underdog = "Oppressé",
	Recover = "Récupérer",
	Gifted = "Talentueux",
	Adrenaline = "Adrenaline",
	Backstabber = "Poignardeur",
	LoneWolf = "Loup Solitaire",
	ReachAdvantage = "Avantage de Portée",
	Overwhelm = "Submerger",
	Relentless = "Infatigable",
	SpecBow = "Maîtrise de l\'arc",
	SpecCrossbow = "Maîtrise de l\'arbalète et des armes à Feu",
	SpecThrowing = "Maîtrise de Lancer",
	SpecAxe = "Maîtrise de la Hache",
	SpecCleaver = "Maîtrise du Hachoir",
	SpecDagger = "Maîtrise de la Dague",
	SpecSword = "Maîtrise de l\'Epée",
	SpecSpear = "Maîtrise de la Lance",
	SpecPolearm = "Maîtrise des Armes d\'Hast",
	SpecHammer = "Maîtrise du Marteau",
	SpecMace = "Maîtrise de la Masse",
	SpecFlail = "Maîtrise du Fléau"
};
gt.Const.Strings.PerkDescription <- {
	Relentless = "Ne ralentissez pas! En tout temps votre Initiative est réduite seulement de [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] de la Fatigue accumulé, au lieu 100%. De plus, utiliser la commande \'Attendre\' ne vous donnera plus de pénalité à votre initiave pour le tour suivant.",
	Rotation = "Débloque la compétence \'Remplacer\' qui permet de permuter deux personnages en ignorant la Zone de Contrôle du moment qu\'aucun des deux personnages n\'est étourdi, enraciné ou invalide.",
	Footwork = "Débloque la compétence \'Jeu de Jambes\' qui permet de de quitter une Zone de Contrôle sans déclencher un jet d\'opportunité en utilisant votre jeu de jambes habile.",
	Debilitate = "Débloque la compétence \'Fragiliser\' qui permet de paralyser la cible pour un tour, réduisant leur capacité à infliger des dégâts par [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color].",
	Indomitable = "Débloque la compétence \'Invincible\' qui permet une réduction de dégâts de [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] et une immunité contre l\'étourdissement, le repoussement ou encore la saisie pendant un tour.",
	RallyTheTroops = "Débloque la compétence \'Rallier\' qui rallie les troupes qui sont en train de fuir, et augmente le morale de tous les alliés à proximité à un niveau raisonable. Plus la détermination du personnage utilisant la compétance est élevée, plus les chances de réussite sont élevés.",
	Adrenaline = "Débloque la compétence \'Adrenaline\' qui vous place en premier au prochain tour, vous permettant d\'avoir un autre tour avant les ennemies. Sentez l\'adrénaline parcourir vos veines!",
	Fearsome = "Faites-les se disperse et s\'enfuir! Toutes les attaques qui infligent au moins 1 de dégâts déclenchent une vérification de morale pour l\'ennemi avec une pénalité égale à [color=" + this.Const.UI.Color.NegativeValue + "]20%[/color] de votre détermination - 10, par contre, si les dégâts sont à 15 ou plus, il n\'y a pas de pénalités.",
	HeadHunter = "Visez la tête! Toucher la tête de votre cible vous garantira de toucher la tête à votre prochaine attaque. Il vous faudra toucher votre cible pour que l\'effet soit réinitialisé.",
	SunderingStrikes = "L\'Efficacité contre l\'armure augmente de [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] pour n\'importe quelle arme utilisé.",
	FastAdaption = "Adaptez vous aux attaques de vos ennemies! Gagnez un stack additionnel de [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] de chance de toucher pour chaque attaque qui manque un ennemie. Le bonus est réinitialisé dès que vous touchez un ennemi.",
	Weaponmaster = "Toutes les attaques coutent [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] de Fatigue à utiliser et la condition des armes se dégrade moitié moins vite. Dancer gracieusement avec votre arme et faites que chaque coup compte. ",
	CoupDeGrace = "Inflige des dégâts additionnels de [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] contre les ennemis qui ont subis n\'importe quelle blessure comme un bras cassé.",
	SteelBrow = "Les coups à la tête n\'infligent maintenant plus de coups critique à ce personnage, ce qui diminue par la même occasion la probabilité de subir des blessures invalidantes à la tête de manière significative.",
	Anticipation = "Quand vous êtes attaqué par des armes à distance, vous gagnez [color=" + this.Const.UI.Color.PositiveValue + "]1 + 10% de votre Défense à Distance[/color] en défense à Distance additionnel par case de distance d\'où se trouve l\'attaquant, et toujours au minimum un bonus de [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] en Défense à Distance.",
	HoldOut = "Tenez le Coup! Tous les status négatifs ont une durée prédéfini (par exemple Saignement, Charmé) ont leur durée réduite de [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] tour. Les Status qui ont leurs effets réduits au fur et à mesure du temps (par exemple Le poison Goblin) sont dans leur état le plus faible dès le début.",
	Dodge = "Trop rapide pour toi! Gagnez [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] de l\'initiative du personnage en tant que bonus de Défense (Mêlée et à Distance).",
	Nimble = "Vous êtes spécialisé en armure légère! En déviant et en esquivant agilement les attaques, transforme les coups en coups faibles. Les points de vie subis sont réduits jusqu\'à un maximum de [color=" + this.Const.UI.Color.PositiveValue + "]60%[/color], mais est diminué exponentiellement par le malus de Fatigue Maximum de l\'armure (tête et corps) au dessus de [color=" + this.Const.UI.Color.PositiveValue + "]15[/color]. Plus votre armure est légère, plus vous en bénéficierez.\n\nMusculeux n\'affecte pas ce Talent.\n\nN\'affecte pas les attaques mentales et les Effets de Status, mais peut aider à les esquiver.",
	BattleForged = "Vous êtes spécialisé en armure lourd! Les dégats d\'armure sont réduits pars un pourcentage égale à [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] du total de la valeur de l\'armure (tête et corps). Le plus lourd l\'armure et le casque, le meilleur le bénéfice.\n\nN\'affecte pas les attaques mentales et les Effets de Status, mais peut aider à les esquiver.",
	Duelist = "Devenez un avec votre arme et visez les points faibles! Quand vous avez une main libre ou avec un outil jetable (exemple Filer à jeter), vous aurez un bonus supplémentaire de [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] qui ignorera l\'armure. Ne fonctionne pas avec les armes à deux mains.",
	CripplingStrikes = "Handicaper vos ennemis! Diminue la probabilité minimum pour infliger des blessures par [color=" + this.Const.UI.Color.NegativeValue + "]33%[/color] pour les armes de mêlée et les armes à distance.",
	QuickHands = "Vous cherchiez quelque chose? Echanger un objet (sauf les boucliers) devient une action gratuite et ne consomme as de points d\'action (Une fois par tour seulement).",
	Bullseye = "C\'est réglé! La pénalité de toucher un ennemi pour lequel vous n\'avez pas d\'angle de tir passe à [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] au lieu de [color=" + this.Const.UI.Color.NegativeValue + "]75%[/color] pour les armes à distance.",
	Ballistics = "The range penalty to hitchance is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] per tile.",
	Berserk = "RAAARGH! Une fois par tour, en tuant un ennemi, [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] Points d\'Action sont récupérés immédiatement. Les personnages ne peuvent regagner plus que leur nombre de points d\'action maximum.",
	BattleFlow = "Once per turn, killing an opponent reduces current fatigue by [color=" + this.Const.UI.Color.NegativeValue + "]-25%[/color] of the base maximum fatigue (before penalties due to armor are applied).",
	DevastatingStrikes = "All damage inflicted is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] for any weapon used. What could stand before you now?",
	KillingFrenzy = "Rentrez dans une Frénésie Sanguinaire! Un ennemie tué augmente tous les dégâts de [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] pour 2 tours. Ne se cumule pas, mais un nouveau tué réinitialisera le décompte.",
	ShieldBash = "The Knock Back skill now also inflicts [color=" + this.Const.UI.Color.DamageValue + "]10 - 25[/color] Damage (50% effective against armor) and [color=" + this.Const.UI.Color.DamageValue + "]10[/color] Fatigue in addition to its normal effect, and costs 10 Fatigue less to use.",
	Brawny = "La pénalité de Fatigue et d\'Initiative en portant une armure et un casque sont réduit de [color=" + this.Const.UI.Color.NegativeValue + "]30%[/color].",
	Stalwart = "Immunity against being knocked back or pulled up close. Applies to skills such as Knock Back, Hook and others that change a character\'s position.",
	Steadfast = "Getting hit by regular attacks does not cause a loss of fatigue anymore. Attacks that specifically target fatigue are unaffected.",
	Taunt = "Débloque la compétence \'Provoquer\' qui fait prendre une position offensive plutôt que défensive pour l\'ennemi ciblé, l\'ennemi cible attaquera en priorité le personnage utilisant Provoquer, ce qui permettrait de proteger une cible plus vulnérable.",
	Colossus = "Amenez-les! Les Points de vie sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color], ce qui permet de diminuer la probabilité de subir des blessures incapacitante quand vous êtes touché.",
	ShieldExpert = "Apprenez à mieux dévier les attaques de côté plutôt que de les bloquer.\n\nLe bonus de défense du bouclier est augmenté de [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]. Cela s\'applique aussi au bonus supplémentaire de Mur de Bouclier.\n\nLes dégâts qui subit le bouclier sint aussi réduits de [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] pour un minimum de 1.\n\nLa Compétence \'Repousser\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] de chance de toucher.",
	NineLives = "Une fois par bataille, en recevant un coup mortel, vous survivrez avec seulement un peu de Points de vie restant et tous les dégâts sur la durée seront soignés (ex. saignement, empoisonement). Bien sûr, le prochain coup sera probablement le dernier pour vous tuer pour de bon mais vous profiterez d\'un bonus de défense jusqu\'au prochain tour pour vous aider à survivre jusque là.",
	BatteringRam = "Immunity against being stunned.",
	BagsAndBelts = "Débloque deux emplacement de sacs supplémentaires pour vous aider à transporter vos objets favoris. Les objets placés dans les sacs ne donnent plus de pénalités au Maximum de Fatigue, sauf pour les armes à deux mains.",
	Student = "Tout peut être appris si vous y mettez de la volonté. Gagnez un bonus additionnel de [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] à l\'experience gagné dans les batailles. Au onzième niveau de votre personnage, celui-ci gagnera un point d\'attour supplémentaire et ce Talent sera désactivé.\n\nEn jouant avec l\'origine \'Traqueur\', vous recevrez vous point de Talent au septième niveau.",
	Gifted = "La vie de mercenaire devient facile quand vous êtes naturellement talentueux. Vous gagnez instantanément un niveau pour augmenter les attributs de ce personnage (avec les meilleurs jets de stat possible), cependant vous ne gagnerez pas de point de Talent.",
	Zweihander = "Fatigue costs for all two-handed weapon skills are reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color].",
	Pathfinder = "Apprenez à vous déplacer sur les terrains accidentés. Les Points d\'Action nécessaires pour vous déplacer sur tous les types de terrains est réduite par [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] pour un minimum de 2 Points d\'Action par tuile, de plus, le coût en Fatigue est divisé par deux. Aussi, changer de hauteur ne coûte maintenant plus de Points d\'Action supplémentaires.",
	FortifiedMind = "Une volonté de fer qui ne se laissera pas détourné du bon chemin facilement. La détermination est augmenté par [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color].",
	Captain = "Nommez un sergeant sur le champ de bataille comme une extention de votre leadership pour garder tout le monde dans les rangs. Les alliés dans un rayon de 5 tuiles ou moins recevront un bonus de [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] de la détermination de ce personnage en plus de le leur, jusqu\'à un maximum de la détermination de ce personnage.\n\nNe se cumule pas; Le sergeant avec la détermination la plus élevée appliquera ce bonus.",
	InspiringPresence = "A great leader of men inspires his followers to overcome their limits. Allies start every battle at confident morale unless prohibited by character traits.",
	Underdog = "J\'y suis habitué. Le malus de défense en étant entouré d\'ennemis ne s\'applique plus à ce personnage. Si l\'ennemi possède le Talent Poignardeur l\'effet de ce Talent est annulé, et le malus de défense en étant entouré est appliqué normalement.",
	Recover = "Débloque la compétence \'Récupérer\' qui permet de se reposer pendant un tour pour réduire la fatigue accumulé par [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color].",
	Backstabber = "L\'Honneur ne vous fait pas gagner de bataille, poignarder un ennemi où ça fait mal si. Le bonus pour toucher en mêlée est augmenté par [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] pour chaque allié entourant et distrayant votre cible.",
	LoneWolf = "Je travaille mieux seul. Si vous n\'avez aucun allié dans un rayon de 3 tuiles de distance, vous gagnez un bonus de [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] en Maîtrise de Mêlée, Maîtrise à distance, Défense en Mêlée, Défense à distance et en Détermination.",
	ReachAdvantage = "Apprenez à vous servir de votre avantage d\'avoir une arme à grande portée pour empêcher les ennemis de se rapprocher pour vous frapper.\n\nChaque coup porté avec une arme de mêlée à deux main rajoute un stack du Talent Avantage de Portée ce qui augmente votre Défense de Mêlée de [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color], jusqu\'à un maximum de 5 stacks, jusqu\'au prochain tour du personnage. Une attaque qui touche plusieurs cibles peut rajouter plusieurs stacks en une fois.\n\nSi vous rangez votre arme vous perdez tous les stacks.",
	Overwhelm = "Apprenez à mieux utiliser votre Initiative en empêchant les ennemies de vous attaquer efficacement en les submergeant avec vos attques!\n\nAvec chaque attaque, touché ou manqué contre un ennemi qui agit après vous dans le tour en cours, lui inflige l\'état \'Submergé\' ce qui diminue sa Maîtrise de mêlée et à distance de [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] pour chaque tour.\n\nL\'effet se stack à chaque attaque, et peut être appliqué à plusieurs cibles en même temps en une seule attaque.",
	SpecBow = "Maîtrisez l\'art de l\'archerie et bombarder les ennemis de flèches depuis une certaine distance. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLa distance de vue et la distance maximale de tir avec les arcs sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	SpecCrossbow = "Maîtrisez les arbalètes et les armes à feu, et apprenez comment avoir une meilleur visée. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nEt [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] de dégâts supplémentaires infligés aves les Arbalètes ignorent l\'armure.\n\nLes Armes de poing ont maintenant besoin de [color=" + this.Const.UI.Color.NegativeValue + "]6[/color] Points d\'Action pour recharger et peuvent tirer à chaque tour et n\'ont plus besoin d\'attendre un tour après avoir recharger pour tirer.",
	SpecThrowing = "Maîtrisez le lancé d\'armes de lancé pour blesser ou tuer les ennemies avant même qu\'ils aient le temps de se rapprocher. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes dégâts sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]30%[/color] en attaquant à 2 tuiles de distance.\n\nLes dégâts sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] en attaquant à 3 tuiles de distance.",
	SpecAxe = "Maîtrisez le combat avec des haches ou de destruction de bouclier. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes dégâts de \'Pourfendre un Bouclier\' sont augmentés de [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] en utilisant des haches.\n\n\'Coup Tournoyant\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance de toucher.\n\nLa Hache Danoise n\'a plus de pénalité en attaquant les cibles au contact.",
	SpecCleaver = "Maîtrisez les fendoirs pour infliger des blessures horrible. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes dégâts de saignement infligés par les fendoirs et les fouets doublés à [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] et [color=" + this.Const.UI.Color.PositiveValue + "]20[/color] par tour, respectivement.\n\nDésarmé a seulement la moitié de la pénalité pour toucher.",
	SpecDagger = "Maîtrise des dagues rapides et mortels. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Poignarder\', \'Percer\' et \'Coup Mortel\' ont un coup en Points d\'Action réduit pour permettre une attaque supplémentaire à chaque tour.",
	SpecSword = "Maîtrisez l\'art du combat à l\'épée et utilisez les erreurs de vos ennemies à votre avantage. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Riposte\' n\'a plus de malus à la probabilité de toucher.\n\n\'Entaille\' a un palier diminué de [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] pour infliger des blessures.\n\n\'Fendre\' et \'Coup d\'épée\' n'ont plus de pénalité de toucher et gagnent [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance en plus de toucher.",
	SpecSpear = "Maîtrisez le combat avec les lances et gardez vos ennemis à distance. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Mur de Lance\' n\'est plus désactivé dans un ennemie arrive à y rentrer. Effectivement, \'Mur de Lance\' peut toujours être utilisé et continue de faire des attaques gratuite à tous les ennemis qui tentent de rentrer dans la zone de contrôle.\n\nLe Spetum and Fourche de Guerre n\'ont plus de pénalité en attaquant les cibles au contact.",
	SpecPolearm = "Maîtrisez les armes d\'hast et gardez l\'ennemi à distance. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\nLes Armes d\'hast ont leur coup en Point d\'action réduit à [color=" + this.Const.UI.Color.NegativeValue + "]5[/color], et n\'ont plus de pénalité en attaquant les cibles au contact.",
	SpecHammer = "Maîtrisez les marteaux et combattez les ennemis en armure lourde. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Détruire l\'Armure\' et \'Destruction d\'Armure\' infligent [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] de dégâts en plus contre l\'armure.\n\n\'Fracasser\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance de toucher.\n\nLe Polehammer n\'a plus de pénalité en attaquant les cibles au contact.",
	SpecMace = "Maîtrisez les massues et soumettez vos ennemis par les coups, qu\'ils soient en armure ou non. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Assomer\', \'Renverser\' et \'Frappe Descendante\' ont [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] de chance d\'étourdir la cible si elle n\'est pas immunisé.\n\nLa Polemace n\'a plus de pénalité en attaquant les cibles au contact.",
	SpecFlail = "Maîtrisez les fléaux et contournez le bouclier de vos ennemis. Les compétences produisent [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] de Fatigue en moins.\n\n\'Coup à la Tête\' et \'Avalanche de Coups à la Tête\' ignorent le bonus de défense des boucliers.\n\nPound ignore [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] d\'armure en plus quand vous touchez la tête.\n\n\'Faucher\' gagne [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] de chance de toucher."
};
gt.Const.Strings.Tooltip <- {
	World = {
		Hint_FocusParty = "Cliquer pour vous concentrer sur le groupe",
		Hint_FocusLocation = "Cliquer pour vous concentrer sur l\'emplacement"
	},
	Tactical = {
		Hint_FocusCharacter = "Cliquer pour vous concentrer sur le personnage",
		Hint_CannotChangeItemInCombat = "Ne peut êtree changé en combat",
		Hint_OnlyActiveCharacterCanChangeItemsInCombat = "Seulement le personnage qui doit agir pendant ce tour peut changer d\'objet"
	}
};
