local gt = this.getroottable();
gt.Const.TipOfTheDay <- [
	"En tant que frères nous combattons, en tant que frères nous mourons !",
	"Les boucliers peuvent être détruits à l'aide de haches et de certaines armes à deux mains.",
	"Les différents types de boucliers sont mieux adaptés aux attaques de mêlée ou à distance.",
	"Les boucliers subissent des dégâts mineurs chaque fois qu'ils sont utilisés pour dévier une attaque.",
	"Les arbustes peuvent cacher les personnages pour qu'ils ne soient pas détectés de loin.",
	"Un personnage ayant un avantage de hauteur sur son adversaire est plus difficile à toucher.",
	"Les personnages peuvent voir plus loin, s'ils sont positionnés haut.",
	"Avoir des hommes d'horizons différents dans votre compagnie peut vous permettre d'effectuer des actions différentes lors d'événements.",
	"Entourer un adversaire de plusieurs côtés permet de porter plus facilement un coup",
	"Pensez à mettre les personnages blessés en réserve jusqu'à ce que leurs blessures soient guéries.",
	"Pensez à constituer une liste de réserve et à faire tourner vos hommes, afin de pouvoir plus facilement faire face à des pertes en cours de route.",
	"La précision des armes à distance diminue avec la distance.",
	"Vous n'avez pas besoin d'être un héros, vous dirigez une compagnie.",
	"Des antécédents différents peuvent débloquer des options supplémentaires pour gérer les événements et les contrats.",
	"Glissez et déposez vos hommes dans l'écran d'inventaire là où vous voulez qu'ils soient dans votre formation.",
	"Une attaque à distance manquée peut toucher des personnages proches, surtout s'ils sont dans la ligne de tir directe.",
	"Les arcs ne peuvent pas tirés et les arbalètes ne peuvent pas être rechargées lorsqu'ils sont engagés en mêlée.",
	"Les arcs sont plus efficaces contre les cibles sans armure.",
	"Les poignards peuvent être utilisés pour attaquer les points faibles des armures et infliger des dégâts directement aux points de vie.",
	"Les armes à distance fonctionnent mieux lorsqu'elles tirent sur des groupes d'ennemis - elles touchent forcément quelqu'un.",
	"Pensez à former un mur de bouclier lorsque vous êtes encerclé.",
	"Conservez votre endurance lors d'engagements prolongés.",
	"Réussir dans Battle Brothers, c'est aussi choisir les bons combats.",
	"Les morts-vivants ne sont pas affectés par la fatigue et le moral.",
	"Les arbalètes nécessitent moins de compétences pour tirer avec précision que les arcs, mais elles sont plus lentes à utiliser.",
	"Chaque type d'arme a des avantages et des inconvénients.",
	"Certains terrains difficiles, comme les marais, donnent des pénalités de combat.",
	"Vous pouvez changer les niveaux de hauteur de la caméra en utilisant les touches + et -.",
	"Les massues et les masses peuvent assommer ou neutraliser les cibles.",
	"Essayez d'économiser quelques couronnes pour quand les choses tourneront mal.",
	"Les épées longues et les épées grises peuvent toucher plusieurs cibles en un seul coup.",
	"Vous pouvez zoomer et dézoomer en utilisant la molette de la souris ou les touches Page précédente et Page suivante.",
	"Les lances sont de bonnes armes défensives grâce à leur capacité de mur de lances.",
	"Attendez-vous à perdre quelques hommes.",
	"Perdre est amusant.",
	"Utilisez le terrain et les points d'étranglement à votre avantage.",
	"Plus leur niveau est élevé, plus vos hommes demanderont un salaire élevé.",
	"Vendre dans les villes riches et grandes vous rapportera plus de couronnes pour vos marchandises.",
	"Utilisez des filets pour limiter le mouvement des ennemis particulièrement dangereux.",
	"Utilisez le commerce pour compléter vos revenus.",
	"Apprenez les avantages Rotation ou Jeu de jambes pour plus de mobilité au combat.",
	"La portée visuelle est réduite la nuit, aussi bien en combat que sur la carte du monde.",
	"Les squelettes sont très résistants aux attaques à distance et aux tirs.",
	"Les armures lourdes offrent une grande protection, mais ralentissent aussi le porteur et le font se fatiguer plus rapidement.",
	"Les casques lourds rend difficiles la respiration et limitent le champ de vision.",
	"Les marteaux de guerre et les piques militaires peuvent faire un travail rapide sur les armures lourdes.",
	"La Serpette la pique et la hache longe peuvent attaquer sur 2 carreaux, contrairement à la plupart des autres armes de mêlée.",
	"Les fléaux ignorent le bonus de défense des boucliers.",
	"Différents types d'ennemis nécessitent différentes tactiques pour être battus de manière fiable.",
	"Chaque ennemi dans le jeu peut être battu de manière fiable avec la bonne approche.",
	"Un humain n'est pas de taille à affronter physiquement un orque adulte.",
	"Les orc comptent sur la puissance brute et les prouesses physiques.",
	"Un gobelin n'est pas de taille face à un humain adulte physiquement, donc ils comptent sur l'esprit et les mauvais tours.",
	"Les berserkers orcs gagnent en rage et deviennent plus difficiles à vaincre, plus ils ont versé de sang.",
	"Les Geists sont perdus entre le monde physique et le monde de l'au-delà, passant constamment de l'un à l'autre.",
	"Les Geists testent la détermination de vos hommes - plus elle est faible, plus ils sont susceptibles de paniquer et de fuir.",
	"Les haches à deux mains peuvent toucher la tête et le corps en un seul coup.",
	"Les haches à deux mains peuvent toucher jusqu'à 6 cibles en un seul coup.",
	"Les routes sont le moyen le plus rapide de voyager sur terre, mais pas toujours le plus sûr.",
	"Les forêts peuvent cacher de nombreux dangers.",
	"Gardez toujours un bon stock de provisions - de peur que vos hommes ne meurent de faim et vous abandonnent !",
	"Les Wiedergangers sont les morts qui marchent à nouveau.",
	"Les terrains difficiles, comme les montagnes et les marais, font que vos hommes utilisent plus de provisions sur la carte du monde.",
	"Si vous ne pouvez pas gagner, battez en retraite pour combattre un autre jour.",
	"Retraite. Fuyez. Ne combattez pas chaque bataille jusqu'à la mort.",
	"Utilisez la barre d'espace pour faire une pause sur la carte du monde.",
	"Les terrains élevés comme les collines et les montagnes vous permettent de voir plus loin sur la carte du monde.",
	"Tous les contrats ne valent pas le risque.",
	"Essayez de négocier un meilleur paiement pour vos contrats.",
	"Essayez de négocier des modalités de paiement qui vous garantissent le plus d'argent pour les contrats.",
	"Toutes les batailles ne peuvent pas être gagnées.",
	"Une vie peut avoir peu de valeur dans ce monde.",
	"Trahir votre employeur peut avoir des répercussions à long terme.",
	"Certaines parties du monde sont plus dangereuses que d'autres.",
	"Utilisez les ports pour voyager rapidement dans le monde.",
	"Certaines personnes vous utiliseront et vous jetteront.",
	"Les armes de jet peuvent être mortelles sur de courtes distances, mais leur précision diminue fortement à mesure que la cible s'éloigne.",
	"Les personnages très talentueux peuvent provenir de tous les milieux.",
	"Essayez le mode Ironman pour vivre Battle Brothers comme il se doit.",
	"Les armes à distance sont moins précises la nuit, y compris celles de vos ennemis",
	"Faites un camp pour que vos hommes guérissent et réparent leur équipement plus rapidement.",
	"Utilisez ALT + Clic droit pour marquer les objets à réparer dans votre cachette. Les objets équipés par vos hommes sont réparés automatiquement.",
	"Vous pouvez faire réparer vos objets chez le forgeron contre rémunération en utilisant ALT + Clic droit.",
	"Rompre un contrat mettra votre employeur en colère - surtout si vous avez reçu un paiement anticipé.",
	"Les fortifications ne vous proposeront que des contrats de la maison noble qui les possède.",
	"Les nobles ne donnent des contrats qu'aux compagnie de mercenaires ayant une renommée professionnelle.",
	"Si les négociations de contrat tournent au vinaigre, cela nuira à vos relations avec votre employeur potentiel.",
	"Vous pouvez trouver des offres de contrat en haut à gauche des écrans de règlement.",
	"Vous pouvez trouver des objets nommés puissants loin de la civilisation en explorant ou en suivant les rumeurs des tavernes.",
	"Mourir fait partie de la description du travail d'un mercenaire.",
	"Gardez un oeil sur l'humeur de vos hommes. S'ils sont en colère pendant trop longtemps, ils peuvent déserter !",
	"Si vous continuez à perdre contre un ennemi, changez de tactique !",
	"Plus une partie est grande sur la carte du monde, plus elle se déplace lentement. La vôtre y compris.",
	"Utilisez des chiens de garde pour traquer les ennemis insaisissables ou en fuite.",
	"Utilisez un faucon dressé pour découvrir des ennemis cachés sur un terrain difficile.",
	"Les fendeurs peuvent infliger des blessures saignantes.",
	"L'accomplissement d'ambitions améliorera l'humeur de tout le monde et vous accordera de la renommée, ainsi que des récompenses uniques.",
	"Utilisez CTRL + Clic gauche pour attaquer les parties alliées sur la carte du monde. Cela ne fonctionne que si vous êtes actuellement sans emploi.",
	"Vos hommes interagiront différemment les uns avec les autres en fonction de leurs antécédents et de leurs traits de caractère",
	"Les personnages assommés ne bénéficient d'aucune attaque d'opportunité lorsque quelqu'un se déplace dans leur zone de contrôle.",
	"Essayez de jouer une campagne en mode vétéran une fois que vous avez acquis de l'expérience - c'est la difficulté recommandée.",
	"La chance de toucher minimale pour toute attaque est de 5 %, et la chance de toucher maximale pour toute attaque est de 95 %.",
	"Les personnages peuvent parfois être terrassés pendant le combat, mais pas tués, et survivront avec une blessure permanente.",
	"Apprenez de vos erreurs. Ne vous contentez pas de les répéter en espérant avoir de la chance cette fois-ci.",
	"L'habitat naturel des loups-garous est la forêt.",
	"Vous pouvez activer des tours d'IA plus rapides dans le menu des options.",
	"Les arbres peuvent être cachés en combat à l'aide de la touche T.",
	"Les objets bloquant les tuiles peuvent être mis en évidence à l'aide de la touche B.",
	"Une renommée plus élevée débloquera des contrats plus difficiles et un meilleur salaire.",
	"Si votre plan peut échouer avec la malchance, peut-être que ce n'est pas un assez bon plan.",
	"Faire le travail. Survivre. être payé.",
	"Si un personnage attend son tour, sa position dans l'ordre du tour suivant est déterminée avec une pénalité de 25% à l'Initiative.",
	"95% de chances de toucher, c'est aussi 5% de chances de rater.",
	"Le talents Loup solitaire n'est pas affecté par les chiens ou alliés proches qui ne font pas partie de votre compagnie.",
	"La compétence Adaptation rapide réduit la variance du hasard.",
	"Considérez que les campements ennemis sur les collines sont plus difficiles à attaquer, surtout s'ils sont fortifiés."
];
gt.Const.LoadingScreens <- [
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_02.jpg",
	"ui/screens/loading_screen_03.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_07.jpg",
	"ui/screens/loading_screen_08.jpg"
];

