this.tundra_elk_enter_event <- this.inherit("scripts/events/event", {
	m = {},
	function create()
	{
		this.m.ID = "event.location.tundra_elk_enter";
		this.m.Title = "As you approach...";
		this.m.Cooldown = 999999.0 * this.World.getTime().SecondsPerDay;
		this.m.IsSpecial = true;
		this.m.Screens.push({
			ID = "A",
			Text = "[img]gfx/ui/events/event_142.png[/img]{Within the barren tundra, you find a prime hunting ground around a small lake, and so you decide to go on a short one-day kill.\n\nYou quickly spot a sizeable elk cropping the scant tundra grass. Just as you ready a kill shot, the elk\'s neck seizes with its snout pointed straight out. The bones crack and its limbs go bow legged as they are gripped by instant death, but it does not fall. The withers tremble and then bulb and shift as though fists rolled beneath its fur. Suddenly, the flesh tears asunder and you can see a slick blue mass bubbling between the wounds. Its legs burst apart and the torso rises high into the air as long stalks of thick bone clap to the ground and wormy, snakelike straps of muscle wrap about the shafts. You believed the elk dead, but its maw groans wildly just as its face rips apart from crown to jaw like a blossoming flower. The face of something else entirely emerges, and it pushes forward as though generated by the very gore it was busy reaping. As the new monster finds its strength, it seizes up on both hind legs and reaches his hands back to tear away the fur of the elk like a man would a cloak. Blood and bones splatter.\n\n A hideous beast three times the height of any man turns and feels out its limbs, tensing its hands, cracking its knees and shoulders, turning its head from side to side with its fat nostrils flaring like a bull. The eye sockets are all bone and a blue haze pulses within them like crackling storms. The elk\'s beautiful antlers have been abrogated by horrible horns. A frosty air curls from its mouth and you can see the leaves of a nearby tree go cold and brittle. \n\n You have the uneasy feeling that this monster is not in fact a monster at all, but a transient spirit which manifests itself as it sees fit, carving itself into the world as an aspect of chaos and little else. Just as you think this, the beast turns its head toward you and it hooks its long nails into the corners of its fanged mouth and stretches the lips so far out the corners could be its ears.%SPEECH_ON%Ahhh, this is the place to be, this is the place where I am happy. Why do you look with such fear, am I not but a simple deer?%SPEECH_OFF%Its head cocks to a side with the drool slopping over its bottom lip and playful tears fill its eyes. You\'ve heard stories of this creature, a cruel horror the northerners call the Ijirok or the Beast of Winter. You know it is not here to speak poetry and play games. You draw your sword, but then a hand claps your shoulder.%SPEECH_ON%Here with you always, captain.%SPEECH_OFF%You turn to see the company at your side and ready to fight.}",
			Image = "",
			List = [],
			Characters = [],
			Options = [
				{
					Text = "We\'ll destroy this thing!",
					function getResult( _event )
					{
						if (this.World.State.getLastLocation() != null)
						{
							this.World.State.getLastLocation().setAttackable(true);
							this.World.State.getLastLocation().setFaction(this.World.FactionManager.getFactionOfType(this.Const.FactionType.Beasts).getID());
						}

						this.World.Events.showCombatDialog(true, true, true);
						return 0;
					}

				},
				{
					Text = "We need to get out of here! Fast!",
					function getResult( _event )
					{
						if (this.World.State.getLastLocation() != null)
						{
							this.World.State.getLastLocation().setVisited(false);
						}

						return 0;
					}

				}
			],
			function start( _event )
			{
			}

		});
	}

	function onUpdateScore()
	{
	}

	function onPrepare()
	{
	}

	function onPrepareVariables( _vars )
	{
	}

	function onClear()
	{
	}

});

